// @ts-nocheck -- generated by npm run functions:build from source.ts; do not edit

// src/bank/server/admobSsv.ts
var ADMOB_KEYS_URL = "https://www.gstatic.com/admob/reward/verifier-keys.json";
var b64urlToBytes = (s) => {
  const b64 = s.replace(/-/g, "+").replace(/_/g, "/");
  const bin = atob(b64 + "=".repeat((4 - b64.length % 4) % 4));
  return Uint8Array.from(bin, (c) => c.charCodeAt(0));
};
function derToRaw(der, size = 32) {
  let i = 0;
  if (der[i++] !== 48) return null;
  let len = der[i++];
  if (len & 128) i += len & 127;
  const out = new Uint8Array(size * 2);
  for (let part = 0; part < 2; part++) {
    if (der[i++] !== 2) return null;
    len = der[i++];
    let int = der.subarray(i, i + len);
    i += len;
    while (int.length > size && int[0] === 0) int = int.subarray(1);
    if (int.length > size) return null;
    out.set(int, part * size + (size - int.length));
  }
  return out;
}
async function importAdmobKeys(json2) {
  const keys2 = /* @__PURE__ */ new Map();
  const list = json2?.keys ?? [];
  for (const k of list) {
    if (typeof k.base64 !== "string" || k.keyId === void 0) continue;
    const der = Uint8Array.from(atob(k.base64), (c) => c.charCodeAt(0));
    keys2.set(String(k.keyId), await crypto.subtle.importKey("spki", der, { name: "ECDSA", namedCurve: "P-256" }, false, ["verify"]));
  }
  return keys2;
}
async function verifyAdmobSsv(rawQuery, keys2) {
  const cut = rawQuery.indexOf("&signature=");
  if (cut <= 0) return { ok: false, reason: "malformed" };
  const message = rawQuery.slice(0, cut);
  const q = new URLSearchParams(rawQuery);
  const signature = q.get("signature");
  const keyId = q.get("key_id");
  if (!signature || !keyId) return { ok: false, reason: "malformed" };
  const key = keys2.get(keyId);
  if (!key) return { ok: false, reason: "unknown_key" };
  let raw;
  try {
    raw = derToRaw(b64urlToBytes(signature));
  } catch {
    return { ok: false, reason: "malformed" };
  }
  if (!raw) return { ok: false, reason: "malformed" };
  const valid = await crypto.subtle.verify({ name: "ECDSA", hash: "SHA-256" }, key, raw, new TextEncoder().encode(message));
  if (!valid) return { ok: false, reason: "bad_signature" };
  const g = (k) => q.get(k) ?? "";
  return {
    ok: true,
    params: {
      adNetwork: g("ad_network"),
      adUnit: g("ad_unit"),
      customData: g("custom_data"),
      rewardAmount: g("reward_amount"),
      rewardItem: g("reward_item"),
      timestamp: g("timestamp"),
      transactionId: g("transaction_id"),
      userId: g("user_id"),
      keyId
    }
  };
}
var UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var json = (status, body) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });
function createSsvHandler(deps) {
  return async (req) => {
    if (req.method !== "GET") return json(405, { error: "method" });
    const url = req.url;
    const rawQuery = url.includes("?") ? url.slice(url.indexOf("?") + 1) : "";
    let verdict = await verifyAdmobSsv(rawQuery, await deps.keys());
    if (!verdict.ok && verdict.reason === "unknown_key") verdict = await verifyAdmobSsv(rawQuery, await deps.keys(true));
    if (!verdict.ok) return json(verdict.reason === "malformed" ? 400 : 403, { error: verdict.reason });
    const p = verdict.params;
    if (!p.userId && !p.transactionId) return json(200, { result: "verified" });
    if (!UUID.test(p.userId) || !p.transactionId) return json(200, { result: "ignored", reason: "no_player" });
    if (deps.adUnit && p.adUnit !== deps.adUnit) return json(200, { result: "ignored", reason: "other_ad_unit" });
    const r = await deps.grant(p.userId.toLowerCase(), p.transactionId);
    if (!r.ok) return r.code === "P0404" ? json(200, { result: "ignored", reason: "no_such_user" }) : json(500, { error: "server" });
    return json(200, { result: r.status, reason: r.reason, replayed: r.replayed });
  };
}

// supabase/functions/admob-ssv/source.ts
var SUPABASE_URL = Deno.env.get("SUPABASE_URL");
var SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
var KEYS_TTL_MS = 12 * 60 * 60 * 1e3;
var cached = null;
async function keys(refresh = false) {
  if (!refresh && cached && Date.now() - cached.at < KEYS_TTL_MS) return cached.keys;
  if (refresh && cached && Date.now() - cached.at < 6e4) return cached.keys;
  const res = await fetch(ADMOB_KEYS_URL);
  if (!res.ok) {
    if (cached) return cached.keys;
    throw new Error("keys unavailable");
  }
  cached = { at: Date.now(), keys: await importAdmobKeys(await res.json()) };
  return cached.keys;
}
var handler = createSsvHandler({
  keys,
  adUnit: Deno.env.get("ADMOB_AD_UNIT") || null,
  async grant(userId, transactionId) {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/bank_grant_ad_reward`, {
      method: "POST",
      headers: { "content-type": "application/json", apikey: SERVICE_KEY, authorization: `Bearer ${SERVICE_KEY}` },
      body: JSON.stringify({ p_user: userId, p_provider: "admob", p_reward_id: transactionId })
    });
    const body = await res.json().catch(() => null);
    if (!res.ok) return { ok: false, code: String(body?.code ?? res.status) };
    const row = body[0];
    return row ? { ok: true, status: row.status, reason: row.reason, replayed: row.replayed } : { ok: false, code: "empty" };
  }
});
Deno.serve(async (req) => {
  try {
    return await handler(req);
  } catch {
    return new Response(JSON.stringify({ error: "server" }), { status: 500, headers: { "content-type": "application/json" } });
  }
});
