// @ts-nocheck -- generated by npm run functions:build from source.ts; do not edit

// src/discord/giveawayHandler.ts
var SNOWFLAKE = /^[0-9]{15,22}$/;
var UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var PLACEHOLDER = /^\{[^{}]*\}$/;
var ID_KEYS = ["guildId", "channelId", "messageId", "discordUserId", "guild_id", "channel_id", "message_id", "discord_user_id", "user_id", "userId"];
var BIG_ID = new RegExp(`("(?:${ID_KEYS.join("|")})"\\s*:\\s*)(-?\\d{16,})(?=\\s*[,}\\]])`, "g");
var BARE_VARIABLE = /(:\s*)\{([A-Za-z0-9_.]+)\}(?=\s*[,}\]])/g;
var MESSAGES = {
  bad_request: "La petici\xF3n no es JSON v\xE1lido.",
  payload_too_large: "La petici\xF3n es demasiado grande.",
  method_not_allowed: "M\xE9todo no permitido: usa POST.",
  unknown_operation: "Operaci\xF3n desconocida.",
  missing_secret: "Falta la cabecera X-BotGhost-Secret.",
  forbidden: "X-BotGhost-Secret no es v\xE1lido.",
  bot_not_configured: "El secreto del bot no est\xE1 configurado en el servidor.",
  unauthorized: "Inicia sesi\xF3n con una cuenta registrada.",
  unresolved_variable: "Una variable de BotGhost no se reemplaz\xF3.",
  invalid_discord_id: "ID de Discord no v\xE1lido (debe tener entre 15 y 22 d\xEDgitos).",
  invalid_giveaway_id: "giveawayId no v\xE1lido.",
  invalid_prize: "prizeCoins debe ser un n\xFAmero entero entre 1 y 1,000,000,000.",
  invalid_ends_at: "La fecha de fin no es v\xE1lida: debe ser futura (m\xE1s de 1 minuto) y como m\xE1ximo a 90 d\xEDas.",
  invalid_request: "Petici\xF3n no v\xE1lida.",
  missing_field: "Falta un campo obligatorio.",
  active_giveaway_exists: "Ya hay un giveaway activo. Solo puede haber uno a la vez.",
  giveaway_not_found: "No existe ese giveaway.",
  no_active_giveaway: "No hay ning\xFAn giveaway activo.",
  account_required: "Tu cuenta de Carta Casino debe estar registrada y con el correo confirmado.",
  database_error: "Error de la base de datos.",
  database_unreachable: "No se pudo contactar con la base de datos.",
  server: "Error interno del servidor.",
  discord_not_linked: "Tu cuenta de Discord no est\xE1 vinculada a Carta Casino. Vinc\xFAlala en la app Carta Casino: Perfil \u2192 Discord \u2192 Vincular.",
  giveaway_closed: "Este giveaway ya termin\xF3.",
  giveaway_ended: "Este giveaway ya termin\xF3.",
  giveaway_still_active: "El giveaway sigue activo.",
  no_expired_giveaway: "No hay giveaways terminados pendientes de sorteo.",
  no_entries: "El giveaway termin\xF3 sin participantes v\xE1lidos.",
  already_awarded: "Este giveaway ya fue premiado.",
  already_ended: "Este giveaway ya termin\xF3 sin ganador.",
  not_an_entry: "Ese usuario no particip\xF3 en el giveaway.",
  invalid_or_expired_code: "El c\xF3digo no es v\xE1lido o caduc\xF3.",
  discord_already_linked: "Esa cuenta de Discord ya est\xE1 vinculada a otra cuenta de Carta.",
  account_already_linked: "Esa cuenta de Carta ya est\xE1 vinculada a otra cuenta de Discord.",
  enter_ok: "\u2705 \xA1Ya est\xE1s participando en el sorteo!",
  link_ok: "\u2705 Tu cuenta de Discord qued\xF3 vinculada a Carta Casino.",
  awarded: "Premio pagado.",
  panel_ok: "Panel del sorteo guardado: el bot lo actualizar\xE1 con cada sorteo nuevo."
};
var message = (code) => MESSAGES[code] ?? code;
var ok = (operation, data = {}, status = 200) => ({ status, body: { ok: true, operation, ...data } });
var fail = (operation, status, code, extra = {}) => ({
  status,
  body: { ok: false, ...operation ? { operation } : {}, code, error: message(code), message: message(code), ...extra }
});
var HttpError = class extends Error {
  constructor(status, code, extra = {}) {
    super(code);
    this.status = status;
    this.code = code;
    this.extra = extra;
  }
};
function parseBody(text) {
  if (!text.trim()) return {};
  const parsed = JSON.parse(text.replace(BIG_ID, '$1"$2"').replace(BARE_VARIABLE, '$1"{$2}"'));
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new SyntaxError("not an object");
  return parsed;
}
var isPlaceholder = (v) => typeof v === "string" && PLACEHOLDER.test(v.trim());
var absent = (v) => v === void 0 || v === null || typeof v === "string" && (v.trim() === "" || isPlaceholder(v));
function pick(body, keys) {
  for (const k of keys) if (body[k] !== void 0) return body[k];
  return void 0;
}
function discordId(body, keys, required) {
  const v = pick(body, keys);
  if (isPlaceholder(v)) throw new HttpError(400, "unresolved_variable", { field: keys[0], value: String(v).trim() });
  if (absent(v)) {
    if (required) throw new HttpError(400, "missing_field", { field: keys[0] });
    return null;
  }
  const s = typeof v === "number" && Number.isSafeInteger(v) ? String(v) : typeof v === "string" ? v.trim() : "";
  if (!SNOWFLAKE.test(s)) throw new HttpError(400, "invalid_discord_id", { field: keys[0] });
  return s;
}
function giveawayId(body, required) {
  const v = pick(body, ["giveawayId", "giveaway_id", "id"]);
  if (isPlaceholder(v)) throw new HttpError(400, "unresolved_variable", { field: "giveawayId", value: String(v).trim() });
  if (absent(v)) {
    if (required) throw new HttpError(400, "missing_field", { field: "giveawayId" });
    return null;
  }
  const s = String(v).trim();
  if (!UUID.test(s)) throw new HttpError(400, "invalid_giveaway_id", { field: "giveawayId" });
  return s;
}
function endsAtFrom(body) {
  const v = pick(body, ["endsAt", "ends_at", "giveaway_end", "giveawayEnd", "endTime", "end_time"]);
  if (absent(v)) return null;
  let ms;
  if (typeof v === "number") ms = v > 1e12 ? v : v * 1e3;
  else if (typeof v === "string") {
    const s = v.trim();
    const tag = /^<t:(\d{9,11})(?::[a-zA-Z])?>$/.exec(s);
    if (tag) ms = Number(tag[1]) * 1e3;
    else if (/^\d{9,13}$/.test(s)) ms = s.length >= 13 ? Number(s) : Number(s) * 1e3;
    else ms = Date.parse(s);
  } else ms = NaN;
  if (!Number.isFinite(ms)) throw new HttpError(400, "invalid_ends_at", { field: "endsAt" });
  return new Date(ms).toISOString();
}
function prizeFrom(body) {
  const v = pick(body, ["prizeCoins", "prize_coins", "prize"]);
  if (absent(v)) return null;
  const n = typeof v === "number" ? v : typeof v === "string" && /^\d+$/.test(v.trim().replace(/[,_]/g, "")) ? Number(v.trim().replace(/[,_]/g, "")) : NaN;
  if (!Number.isSafeInteger(n) || n <= 0 || n > 1e9) throw new HttpError(400, "invalid_prize", { field: "prizeCoins" });
  return n;
}
var unixSeconds = (v) => {
  const ms = typeof v === "string" ? Date.parse(v) : NaN;
  return Number.isFinite(ms) ? Math.floor(ms / 1e3) : null;
};
var coins = (n) => n.toLocaleString("en-US");
function cycleView(data) {
  const d = data ?? {};
  const result = giveawayView(d.result);
  const active = giveawayView(d.active);
  const panel = d.panel ?? {};
  const winner = typeof result?.winnerDiscordUserId === "string" ? result.winnerDiscordUserId : null;
  const prize = Number(result?.prizeCoins ?? 0);
  const announcement = !result ? "" : winner ? `\u{1F3C6} \xA1Felicidades <@${winner}>! Ganaste ${coins(prize)} Carta Coins en el sorteo semanal. Ya est\xE1n en tu cuenta de Carta Casino.` : "El sorteo semanal termin\xF3 sin participantes v\xE1lidos.";
  return {
    hasResult: !!result,
    hasWinner: !!winner,
    announcement,
    winnerDiscordUserId: winner ?? "",
    winnerMention: winner ? `<@${winner}>` : "",
    dmText: winner ? `\u{1F389} \xA1Ganaste el sorteo semanal de Carta Casino! ${coins(prize)} Carta Coins ya est\xE1n en tu cuenta.` : "",
    resultGiveawayId: result?.id ?? "",
    resultPrizeCoins: prize,
    hasActive: !!active,
    giveawayId: active?.id ?? "",
    prizeCoins: Number(active?.prizeCoins ?? 0),
    prizeText: coins(Number(active?.prizeCoins ?? 0)),
    entries: Number(active?.entries ?? 0),
    startsAtUnix: active?.startsAtUnix ?? 0,
    endsAtUnix: active?.endsAtUnix ?? 0,
    hasPanel: typeof panel.messageId === "string" && typeof panel.channelId === "string",
    panelChannelId: typeof panel.channelId === "string" ? panel.channelId : "",
    panelMessageId: typeof panel.messageId === "string" ? panel.messageId : "",
    result,
    active
  };
}
function giveawayView(row) {
  if (!row || typeof row !== "object") return null;
  const r = row;
  if (r.id === void 0 || r.id === null) return null;
  const g = (snake, camel) => r[camel] !== void 0 ? r[camel] : r[snake];
  return {
    id: r.id,
    guildId: g("guild_id", "guildId"),
    channelId: g("channel_id", "channelId"),
    messageId: g("message_id", "messageId") ?? null,
    prizeCoins: Number(g("prize_coins", "prizeCoins")),
    startsAt: g("starts_at", "startsAt"),
    endsAt: g("ends_at", "endsAt"),
    // Unix seconds, for Discord timestamps (<t:1791401400:R>), which show in each reader's own time zone.
    startsAtUnix: unixSeconds(g("starts_at", "startsAt")),
    endsAtUnix: unixSeconds(g("ends_at", "endsAt")),
    status: r.status,
    winnerDiscordUserId: g("winner_discord_user_id", "winnerDiscordUserId") ?? null,
    ...r.entries !== void 0 ? { entries: Number(r.entries) } : {}
  };
}
var firstRow = (v) => Array.isArray(v) ? v[0] ?? null : v;
function timingSafeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}
var STATUS_OF = { P0400: 400, P0401: 401, P0403: 403, P0404: 404, P0409: 409 };
var HARD_STATUSES = /* @__PURE__ */ new Set([401, 403, 405, 413]);
async function handleGiveawayRequest(req, deps) {
  const out = await handle(req, deps);
  if (out.status < 400 || out.status >= 500 || HARD_STATUSES.has(out.status)) return out;
  let soft = false;
  try {
    const body = parseBody(req.body);
    soft = body.alwaysOk === true || body.alwaysOk === "true";
  } catch {
    soft = false;
  }
  return soft ? { status: 200, body: { ...out.body, httpStatus: out.status } } : out;
}
async function handle(req, deps) {
  const log = deps.log ?? (() => {
  });
  let operation = null;
  const call = async (name, args) => {
    const res = await deps.rpc(name, args);
    if (res.ok) return res.data;
    const e = res.error;
    if (e.code === "network") throw new HttpError(503, "database_unreachable");
    const known = STATUS_OF[e.code];
    if (known) throw new HttpError(known, e.message || "invalid_request", e.details ? { detail: e.details } : {});
    if (e.code === "22007" || e.code === "22008") throw new HttpError(400, "invalid_ends_at");
    if (e.code === "22P02") throw new HttpError(400, "invalid_request");
    log(`discord-giveaway ${operation ?? "-"}: database ${e.code} ${e.message}`);
    throw new HttpError(500, "database_error", { dbCode: e.code });
  };
  const current = async () => giveawayView(await call("discord_current_giveaway", {}));
  const outcome = (op, row, extra = {}) => {
    const r = row ?? {};
    const reason = typeof r.reason === "string" ? r.reason : null;
    const body = { ...r, ...extra, ...reason ? { reason, message: message(reason) } : r.ok === true ? { message: message(`${op}_ok`) } : {} };
    return r.ok === true ? ok(op, body) : fail(op, reason === "giveaway_not_found" ? 404 : 409, reason ?? "invalid_request", body);
  };
  try {
    if (req.method === "GET") return ok("health", { service: "discord-giveaway", status: "healthy" });
    if (req.method !== "POST") return fail(null, 405, "method_not_allowed");
    if (req.body.length > 8192) return fail(null, 413, "payload_too_large");
    let body;
    try {
      body = parseBody(req.body);
    } catch {
      return fail(null, 400, "bad_request");
    }
    operation = typeof body.op === "string" ? body.op.trim().toLowerCase() : typeof body.operation === "string" ? body.operation.trim().toLowerCase() : "";
    const op = operation;
    if (op === "link_code") {
      const user = await deps.verifyUser(req.headers["authorization"] ?? "");
      if (!user?.registered) return fail(op, 401, "unauthorized");
      const code = await call("discord_issue_link_code", { p_user: user.id });
      return ok(op, { code });
    }
    const supplied = (req.headers["x-botghost-secret"] ?? "").trim();
    if (!supplied) return fail(op || null, 401, "missing_secret");
    const expected = await deps.botSecretHash();
    if (!expected) return fail(op || null, 503, "bot_not_configured");
    if (supplied.length > 512 || !timingSafeEqual(await deps.sha256Hex(supplied), expected.toLowerCase())) return fail(op || null, 403, "forbidden");
    switch (op) {
      case "link": {
        const discordUserId = discordId(body, ["discordUserId", "discord_user_id", "userId", "user_id"], true);
        const code = String(pick(body, ["code"]) ?? "").trim();
        if (!code || isPlaceholder(code)) throw new HttpError(400, isPlaceholder(code) ? "unresolved_variable" : "missing_field", { field: "code" });
        const row = firstRow(await call("discord_consume_link_code", { p_code: code, p_discord_user_id: discordUserId }));
        return outcome(op, row);
      }
      case "create": {
        const guildId = discordId(body, ["guildId", "guild_id"], true);
        const channelId = discordId(body, ["channelId", "channel_id"], true);
        const messageId = discordId(body, ["messageId", "message_id"], false);
        const prizeCoins = prizeFrom(body);
        const endsAt = endsAtFrom(body);
        try {
          const row = firstRow(
            await call("discord_create_giveaway", { p_guild_id: guildId, p_channel_id: channelId, p_message_id: messageId, p_prize_coins: prizeCoins, p_ends_at: endsAt })
          );
          const giveaway = giveawayView(row);
          if (!giveaway) throw new HttpError(500, "database_error");
          return ok(op, { giveaway, endsAtSource: endsAt ? "request" : "default", prizeSource: prizeCoins !== null ? "request" : "default" });
        } catch (e) {
          if (e instanceof HttpError && e.code === "active_giveaway_exists") {
            return fail(op, 409, "active_giveaway_exists", { activeGiveaway: await current().catch(() => null) });
          }
          throw e;
        }
      }
      case "message": {
        const id = giveawayId(body, false);
        const messageId = discordId(body, ["messageId", "message_id"], true);
        const row = firstRow(await call("discord_set_giveaway_message", { p_giveaway_id: id, p_message_id: messageId }));
        return ok(op, { giveaway: giveawayView(row) });
      }
      case "enter": {
        const discordUserId = discordId(body, ["discordUserId", "discord_user_id", "userId", "user_id"], true);
        const id = giveawayId(body, false);
        const messageId = id ? null : discordId(body, ["messageId", "message_id"], false);
        if (id || !messageId) {
          const target = id ?? (await current())?.id ?? null;
          if (!target) return fail(op, 404, "no_active_giveaway");
          const row2 = firstRow(await call("discord_enter_giveaway", { p_giveaway_id: target, p_discord_user_id: discordUserId }));
          return outcome(op, row2, { giveawayId: target });
        }
        const row = firstRow(await call("discord_enter_giveaway_by_message", { p_message_id: messageId, p_discord_user_id: discordUserId }));
        return outcome(op, row);
      }
      case "entries": {
        const id = giveawayId(body, false) ?? ((await current())?.id ?? null);
        if (!id) return fail(op, 404, "no_active_giveaway");
        const rows = await call("discord_list_entries", { p_giveaway_id: id });
        const entries = Array.isArray(rows) ? rows.map((x) => String(x.discord_user_id)) : [];
        return ok(op, { giveawayId: id, count: entries.length, entries });
      }
      case "draw": {
        const id = giveawayId(body, false);
        const row = firstRow(await call("discord_draw_giveaway", { p_giveaway_id: id }));
        return outcome(op, row);
      }
      case "award": {
        const id = giveawayId(body, true);
        const discordUserId = discordId(body, ["discordUserId", "discord_user_id", "userId", "user_id"], true);
        const row = firstRow(await call("discord_award_giveaway", { p_giveaway_id: id, p_discord_user_id: discordUserId }));
        return outcome(op, row);
      }
      case "status":
      case "current": {
        const id = giveawayId(body, false);
        const discordUserId = discordId(body, ["discordUserId", "discord_user_id", "userId", "user_id"], false);
        let giveaway;
        if (id) {
          const rows = await call("discord_giveaway_by_id", { p_giveaway_id: id });
          giveaway = giveawayView(rows);
          if (!giveaway) return fail(op, 404, "giveaway_not_found");
        } else {
          giveaway = await current();
          if (!giveaway) return fail(op, 404, "no_active_giveaway", { giveaway: null });
        }
        const linked = discordUserId ? await call("discord_is_linked", { p_discord_user_id: discordUserId }) === true : void 0;
        return ok(op, { giveaway, ...linked !== void 0 ? { linked } : {} });
      }
      case "tick": {
        const result = await call("discord_giveaway_tick", {});
        const pending = await call("discord_pending_announcements", {});
        return ok(op, {
          drawn: result?.drawn ?? [],
          created: giveawayView(result?.created),
          active: giveawayView(result?.active),
          pending
        });
      }
      case "panel": {
        const channelId = discordId(body, ["channelId", "channel_id"], true);
        const messageId = discordId(body, ["messageId", "message_id"], true);
        const panel = await call("discord_set_panel", { p_channel_id: channelId, p_message_id: messageId });
        return ok(op, { panel, message: message("panel_ok") });
      }
      case "cycle": {
        return ok(op, cycleView(await call("discord_giveaway_cycle", {})));
      }
      case "pending": {
        const pending = await call("discord_pending_announcements", {});
        return ok(op, { ...pending });
      }
      case "announced": {
        const id = giveawayId(body, true);
        const marked = await call("discord_mark_announced", { p_giveaway_id: id }) === true;
        return marked ? ok(op, { giveawayId: id }) : fail(op, 409, "invalid_request", { giveawayId: id });
      }
      default:
        return fail(op || null, 400, "unknown_operation", { operations: ["link_code", "link", "create", "message", "enter", "entries", "draw", "award", "status", "current", "tick", "cycle", "panel", "pending", "announced"] });
    }
  } catch (e) {
    if (e instanceof HttpError) return fail(operation || null, e.status, e.code, e.extra);
    log(`discord-giveaway ${operation ?? "-"}: ${e instanceof Error ? e.message : String(e)}`);
    return fail(operation || null, 500, "server");
  }
}

// supabase/functions/discord-giveaway/source.ts
var SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
var ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY") ?? "";
var SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
var ALLOWED = /* @__PURE__ */ new Set(["https://siiknotic.github.io", "http://localhost:5173", "http://127.0.0.1:5173", "http://localhost:4173"]);
var admin = { apikey: SERVICE_KEY, authorization: `Bearer ${SERVICE_KEY}`, "content-type": "application/json" };
async function rpc(name, args) {
  let res;
  try {
    res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`, { method: "POST", headers: admin, body: JSON.stringify(args) });
  } catch {
    return { ok: false, error: { status: 0, code: "network", message: "network" } };
  }
  const text = await res.text();
  let body = null;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    body = text;
  }
  if (res.ok) return { ok: true, data: body };
  const b = body && typeof body === "object" ? body : {};
  return { ok: false, error: { status: res.status, code: b.code ?? String(res.status), message: b.message ?? "", details: b.details ?? void 0 } };
}
async function botSecretHash() {
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/discord_bot_config?select=secret_hash&id=eq.true&limit=1`, { headers: admin });
    if (!res.ok) return null;
    const rows = await res.json();
    return typeof rows?.[0]?.secret_hash === "string" ? rows[0].secret_hash : null;
  } catch {
    return null;
  }
}
async function verifyUser(authorization) {
  if (!authorization.startsWith("Bearer ")) return null;
  try {
    const res = await fetch(`${SUPABASE_URL}/auth/v1/user`, { headers: { apikey: ANON_KEY, authorization } });
    if (!res.ok) return null;
    const u = await res.json();
    if (typeof u?.id !== "string") return null;
    return { id: u.id, registered: u.is_anonymous !== true && typeof u.email_confirmed_at === "string" };
  } catch {
    return null;
  }
}
async function sha256Hex(value) {
  const hash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return Array.from(new Uint8Array(hash), (b) => b.toString(16).padStart(2, "0")).join("");
}
function cors(origin) {
  return {
    "access-control-allow-origin": ALLOWED.has(origin) ? origin : "https://siiknotic.github.io",
    "access-control-allow-headers": "authorization, apikey, content-type, x-client-info, x-botghost-secret",
    "access-control-allow-methods": "GET, POST, OPTIONS",
    vary: "origin"
  };
}
Deno.serve(async (req) => {
  const headers = { ...cors(req.headers.get("origin") ?? ""), "cache-control": "no-store", "content-type": "application/json; charset=utf-8" };
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers });
  try {
    const out = await handleGiveawayRequest(
      {
        method: req.method,
        headers: { authorization: req.headers.get("authorization") ?? void 0, "x-botghost-secret": req.headers.get("x-botghost-secret") ?? void 0 },
        body: req.method === "POST" ? await req.text() : ""
      },
      { rpc, botSecretHash, verifyUser, sha256Hex, log: (m) => console.error(m) }
    );
    return new Response(JSON.stringify(out.body), { status: out.status, headers });
  } catch (e) {
    console.error("discord-giveaway: unexpected", e instanceof Error ? e.message : String(e));
    return new Response(JSON.stringify({ ok: false, code: "server", error: "Error interno del servidor." }), { status: 500, headers });
  }
});
