// @ts-nocheck -- generated by npm run functions:build from source.ts; do not edit

// src/account/server/deleteHandler.ts
async function handleDeleteRequest(req, deps2) {
  if (req.method !== "POST") return { status: 405, body: { ok: false, code: "bad_request" } };
  if (!req.user) return { status: 401, body: { ok: false, code: "unauthorized" } };
  const b = req.body ?? {};
  if (b.op !== "delete" || b.confirm !== true) return { status: 400, body: { ok: false, code: "bad_request" } };
  try {
    await deps2.prepare(req.user.id);
  } catch (e) {
    const code = e instanceof Error ? e.message : "server";
    if (code === "owner_protected") return { status: 403, body: { ok: false, code } };
    if (code === "no_such_user") return { status: 404, body: { ok: false, code } };
    return { status: 500, body: { ok: false, code: "server" } };
  }
  await deps2.deleteUser(req.user.id);
  return { status: 200, body: { ok: true } };
}

// supabase/functions/account/source.ts
var SUPABASE_URL = Deno.env.get("SUPABASE_URL");
var ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY");
var SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
var ALLOWED = /* @__PURE__ */ new Set(["https://siiknotic.github.io", "http://localhost:5173", "http://127.0.0.1:5173", "http://localhost:4173"]);
var admin = { apikey: SERVICE_KEY, authorization: `Bearer ${SERVICE_KEY}`, "content-type": "application/json" };
async function verifiedUser(req) {
  const auth = req.headers.get("authorization") ?? "";
  if (!auth.startsWith("Bearer ")) return null;
  const res = await fetch(`${SUPABASE_URL}/auth/v1/user`, { headers: { apikey: ANON_KEY, authorization: auth } });
  if (!res.ok) return null;
  const u = await res.json().catch(() => null);
  return typeof u?.id === "string" ? { id: u.id } : null;
}
var deps = {
  async prepare(userId) {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/account_delete_prepare`, { method: "POST", headers: admin, body: JSON.stringify({ p_user: userId }) });
    if (!res.ok) {
      const body = await res.json().catch(() => null);
      throw new Error(body?.message === "owner_protected" || body?.message === "no_such_user" ? body.message : "server");
    }
  },
  async deleteUser(userId) {
    const res = await fetch(`${SUPABASE_URL}/auth/v1/admin/users/${userId}`, { method: "DELETE", headers: admin });
    if (!res.ok) throw new Error(`delete failed: ${res.status}`);
  }
};
Deno.serve(async (req) => {
  const origin = req.headers.get("origin") ?? "";
  const cors = {
    "access-control-allow-origin": ALLOWED.has(origin) ? origin : "https://siiknotic.github.io",
    "access-control-allow-headers": "authorization, apikey, content-type, x-client-info",
    "access-control-allow-methods": "POST, OPTIONS",
    vary: "origin"
  };
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
  let body = null;
  const text = await req.text();
  if (text.length > 1024) return Response.json({ ok: false, code: "bad_request" }, { status: 413, headers: cors });
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    return Response.json({ ok: false, code: "bad_request" }, { status: 400, headers: cors });
  }
  try {
    const out = await handleDeleteRequest({ method: req.method, user: await verifiedUser(req), body }, deps);
    return Response.json(out.body, { status: out.status, headers: { ...cors, "cache-control": "no-store" } });
  } catch (e) {
    console.error("account", e instanceof Error ? e.message : e);
    return Response.json({ ok: false, code: "server" }, { status: 500, headers: cors });
  }
});
