// @ts-nocheck -- generated by npm run functions:build from source.ts; do not edit

// src/game/engine/rng.ts
function createRng(state) {
  let s = state >>> 0;
  return {
    next() {
      s = s + 1831565813 >>> 0;
      let t = s;
      t = Math.imul(t ^ t >>> 15, t | 1);
      t ^= t + Math.imul(t ^ t >>> 7, t | 61);
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    },
    state() {
      return s;
    }
  };
}

// src/games/shared/rng.ts
function shuffle(items, rng) {
  const out = [...items];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng.next() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}
function hashSeed(text) {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

// src/games/domino/engine/rules.ts
var MAX_PIP = 6;
var PLAYERS_MIN = 2;
var PLAYERS_MAX = 4;
var HAND_SIZE = 7;
var DEFAULT_TARGET = 100;
function tileId(a, b) {
  return a <= b ? `${a}-${b}` : `${b}-${a}`;
}
function fullSet() {
  const out = [];
  for (let a = 0; a <= MAX_PIP; a++) for (let b = a; b <= MAX_PIP; b++) out.push({ id: tileId(a, b), a, b });
  return out;
}
var isDouble = (t) => t.a === t.b;
var pipsOf = (t) => t.a + t.b;
var handPips = (hand) => hand.reduce((s, t) => s + pipsOf(t), 0);
function openEnds(line) {
  if (line.length === 0) return null;
  return { left: line[0].left, right: line[line.length - 1].right };
}
var fits = (t, pip) => t.a === pip || t.b === pip;
function endsFor(t, line) {
  const ends = openEnds(line);
  if (!ends) return ["right"];
  const out = [];
  if (fits(t, ends.left)) out.push("left");
  if (fits(t, ends.right)) out.push("right");
  return out;
}
function legalMoves(ctx) {
  const { playerId, hand, line, boneyardCount, mustLead } = ctx;
  const plays = [];
  for (const t of hand) {
    if (line.length === 0 && mustLead && t.id !== mustLead) continue;
    for (const end of endsFor(t, line)) plays.push({ type: "PLAY_TILE", playerId, tileId: t.id, end });
  }
  if (plays.length > 0) return plays;
  return [boneyardCount > 0 ? { type: "DRAW", playerId } : { type: "PASS", playerId }];
}
function placeAt(t, end, line, by, seq) {
  const ends = openEnds(line);
  if (!ends) return { tile: t, left: t.a, right: t.b, by, seq };
  if (end === "right") {
    const join2 = ends.right;
    return { tile: t, left: join2, right: t.a === join2 ? t.b : t.a, by, seq };
  }
  const join = ends.left;
  return { tile: t, left: t.a === join ? t.b : t.a, right: join, by, seq };
}
function openingTile(hands) {
  let best = null;
  hands.forEach((hand, seat) => {
    for (const t of hand) {
      const rank = isDouble(t) ? 1e3 + t.a : pipsOf(t) * 10 + Math.max(t.a, t.b);
      if (!best || rank > best.rank) best = { seat, tile: t, rank };
    }
  });
  if (!best) throw new Error("no tiles dealt");
  const b = best;
  return { seat: b.seat, tile: b.tile };
}

// src/games/domino/engine/game.ts
function createDomino(config) {
  const n = config.seats.length;
  if (n < PLAYERS_MIN || n > PLAYERS_MAX) throw new Error(`Domino needs ${PLAYERS_MIN}-${PLAYERS_MAX} players`);
  if (new Set(config.seats.map((s) => s.id)).size !== n) throw new Error("Seat ids must be unique");
  const base = {
    version: 1,
    seed: config.seed >>> 0,
    rngState: config.seed >>> 0,
    round: 0,
    status: "playing",
    settings: { targetScore: config.targetScore ?? DEFAULT_TARGET },
    players: config.seats.map((s) => ({ id: s.id, name: s.name, kind: s.kind, hand: [] })),
    boneyard: [],
    line: [],
    current: 0,
    mustLead: null,
    lacks: {},
    scores: Object.fromEntries(config.seats.map((s) => [s.id, 0])),
    lastResult: null,
    matchWinners: [],
    turn: 0
  };
  return dealRound(base, null).state;
}
function dealRound(prev, leaderId) {
  const rng = createRng(prev.rngState);
  const tiles = shuffle(fullSet(), rng);
  const players = prev.players.map((p, i) => ({ ...p, hand: tiles.slice(i * HAND_SIZE, (i + 1) * HAND_SIZE) }));
  const boneyard = tiles.slice(players.length * HAND_SIZE);
  let current;
  let mustLead = null;
  const leaderSeat = leaderId ? players.findIndex((p) => p.id === leaderId) : -1;
  if (leaderSeat >= 0) current = leaderSeat;
  else {
    const open = openingTile(players.map((p) => p.hand));
    current = open.seat;
    mustLead = open.tile.id;
  }
  const state = {
    ...prev,
    rngState: rng.state(),
    round: prev.round + 1,
    status: "playing",
    players,
    boneyard,
    line: [],
    current,
    mustLead,
    lacks: Object.fromEntries(players.map((p) => [p.id, []])),
    lastResult: null
  };
  return { state, events: [{ type: "dealt", round: state.round, leaderId: players[current].id }] };
}
function currentPlayer(state) {
  return state.players[state.current];
}
function legalActionsFor(state, playerId) {
  if (state.status === "round_over") return [{ type: "NEXT_ROUND", playerId }];
  if (state.status !== "playing" || currentPlayer(state).id !== playerId) return [];
  const p = currentPlayer(state);
  return legalMoves({ playerId, hand: p.hand, line: state.line, boneyardCount: state.boneyard.length, mustLead: state.mustLead });
}
function validateDomino(state, action) {
  const player = state.players.find((p) => p.id === action.playerId);
  if (!player) return "unknown_player";
  if (action.type === "NEXT_ROUND") return state.status === "round_over" ? null : "round_not_over";
  if (state.status !== "playing") return "not_playing";
  if (currentPlayer(state).id !== player.id) return "not_your_turn";
  const legal = legalActionsFor(state, player.id);
  const canPlay = legal.some((a) => a.type === "PLAY_TILE");
  switch (action.type) {
    case "PLAY_TILE": {
      const tile = player.hand.find((t) => t.id === action.tileId);
      if (!tile) return "tile_not_in_hand";
      if (state.line.length === 0 && state.mustLead && tile.id !== state.mustLead) return "must_lead";
      return endsFor(tile, state.line).includes(action.end) || state.line.length === 0 && action.end === "left" ? null : "no_match";
    }
    case "DRAW":
      if (canPlay) return "must_play";
      return state.boneyard.length > 0 ? null : "boneyard_empty";
    case "PASS":
      if (canPlay) return "must_play";
      return state.boneyard.length > 0 ? "must_draw" : null;
  }
}
var addLack = (lacks, id, pips) => ({
  ...lacks,
  [id]: [.../* @__PURE__ */ new Set([...lacks[id] ?? [], ...pips])].sort((x, y) => x - y)
});
function applyDomino(state, action) {
  const error = validateDomino(state, action);
  if (error) return { ok: false, error };
  if (action.type === "NEXT_ROUND") {
    const dealt = dealRound({ ...state, turn: state.turn + 1 }, state.lastResult?.winnerId ?? null);
    return { ok: true, state: dealt.state, events: [...dealt.events, { type: "turn", playerId: currentPlayer(dealt.state).id }] };
  }
  const events = [];
  let next = { ...state, turn: state.turn + 1 };
  const me = currentPlayer(state);
  const ends = openEnds(state.line);
  if (action.type === "PLAY_TILE") {
    const tile = me.hand.find((t) => t.id === action.tileId);
    const placed = placeAt(tile, action.end, state.line, me.id, state.line.length);
    const line = state.line.length === 0 || action.end === "right" ? [...state.line, placed] : [placed, ...state.line];
    next = {
      ...next,
      line,
      mustLead: null,
      players: state.players.map((p) => p.id === me.id ? { ...p, hand: p.hand.filter((t) => t.id !== tile.id) } : p)
    };
    events.push({ type: "played", playerId: me.id, tileId: tile.id, end: action.end, seq: placed.seq });
    if (next.players[state.current].hand.length === 0) return finishRound(next, events, me.id, "domino");
  } else if (action.type === "DRAW") {
    const [drawn, ...rest] = state.boneyard;
    next = {
      ...next,
      boneyard: rest,
      players: state.players.map((p) => p.id === me.id ? { ...p, hand: [...p.hand, drawn] } : p),
      lacks: ends ? addLack(state.lacks, me.id, [ends.left, ends.right]) : state.lacks
    };
    events.push({ type: "drew", playerId: me.id });
    return { ok: true, state: next, events };
  } else {
    next = { ...next, lacks: ends ? addLack(state.lacks, me.id, [ends.left, ends.right]) : state.lacks };
    events.push({ type: "passed", playerId: me.id });
  }
  if (isBlocked(next)) return finishRound(next, events, null, "blocked");
  next = { ...next, current: (state.current + 1) % state.players.length };
  events.push({ type: "turn", playerId: currentPlayer(next).id });
  return { ok: true, state: next, events };
}
function isBlocked(state) {
  if (state.boneyard.length > 0 || state.line.length === 0) return false;
  const ends = openEnds(state.line);
  return state.players.every((p) => p.hand.every((t) => t.a !== ends.left && t.b !== ends.left && t.a !== ends.right && t.b !== ends.right));
}
function finishRound(state, events, dominoBy, reason) {
  const pips = Object.fromEntries(state.players.map((p) => [p.id, handPips(p.hand)]));
  let winnerId = dominoBy;
  if (!winnerId) {
    const low = Math.min(...Object.values(pips));
    const lowest = state.players.filter((p) => pips[p.id] === low);
    winnerId = lowest.length === 1 ? lowest[0].id : null;
  }
  const points = winnerId ? state.players.filter((p) => p.id !== winnerId).reduce((s, p) => s + pips[p.id], 0) : 0;
  const scores = winnerId ? { ...state.scores, [winnerId]: state.scores[winnerId] + points } : state.scores;
  const result = { round: state.round, winnerId, reason, points, pips };
  const top = Math.max(...Object.values(scores));
  const over = top >= state.settings.targetScore;
  const matchWinners = over ? state.players.filter((p) => scores[p.id] === top).map((p) => p.id) : [];
  const next = { ...state, scores, lastResult: result, status: over ? "game_over" : "round_over", matchWinners };
  events.push({ type: "round_over", result });
  if (over) events.push({ type: "game_over", winners: matchWinners });
  return { ok: true, state: next, events };
}
function rematch(state, seed) {
  return createDomino({ seats: state.players.map(({ id, name, kind }) => ({ id, name, kind })), seed, targetScore: state.settings.targetScore });
}

// src/games/domino/engine/parse.ts
var ID = /^[A-Za-z0-9_-]{1,32}$/;
var TILE = /^[0-6]-[0-6]$/;
function parseDominoAction(raw) {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return null;
  const r = raw;
  if (typeof r.playerId !== "string" || !ID.test(r.playerId)) return null;
  const keys = Object.keys(r).sort().join(",");
  switch (r.type) {
    case "PLAY_TILE":
      if (keys !== "end,playerId,tileId,type") return null;
      if (typeof r.tileId !== "string" || !TILE.test(r.tileId) || r.end !== "left" && r.end !== "right") return null;
      return { type: "PLAY_TILE", playerId: r.playerId, tileId: r.tileId, end: r.end };
    case "DRAW":
    case "PASS":
    case "NEXT_ROUND":
      if (keys !== "playerId,type") return null;
      return { type: r.type, playerId: r.playerId };
    default:
      return null;
  }
}

// src/games/domino/engine/view.ts
function dominoView(state, me) {
  const self = state.players.find((p) => p.id === me);
  const current = state.players[state.current];
  const view = {
    me,
    hand: self ? self.hand.map((t) => ({ ...t })) : [],
    seats: state.players.map((p) => ({ id: p.id, name: p.name, kind: p.kind, tiles: p.hand.length, score: state.scores[p.id] ?? 0, lacks: [...state.lacks[p.id] ?? []] })),
    line: state.line.map((t) => ({ ...t, tile: { ...t.tile } })),
    boneyardCount: state.boneyard.length,
    currentId: current.id,
    status: state.status,
    round: state.round,
    targetScore: state.settings.targetScore,
    // Only the seat holding the required opening tile learns which tile it is.
    mustLead: self && state.mustLead && self.hand.some((t) => t.id === state.mustLead) ? state.mustLead : null,
    lastResult: state.lastResult ? { ...state.lastResult, pips: { ...state.lastResult.pips } } : null,
    matchWinners: [...state.matchWinners],
    turn: state.turn,
    legal: []
  };
  if (self && state.status === "playing" && current.id === me) {
    view.legal = legalMoves({ playerId: me, hand: self.hand, line: state.line, boneyardCount: state.boneyard.length, mustLead: state.mustLead });
  } else if (self && state.status === "round_over") view.legal = [{ type: "NEXT_ROUND", playerId: me }];
  return view;
}

// src/games/bingo/engine/types.ts
var CELLS = 25;
var CENTER = 12;
var BALLS = 75;

// src/games/bingo/engine/rules.ts
var PLAYERS_MIN2 = 1;
var PLAYERS_MAX2 = 4;
var ROUND_POINTS = 100;
var FALSE_CLAIM_PENALTY = 3;
function generateCard(rng) {
  const card = new Array(CELLS).fill(0);
  for (let col = 0; col < 5; col++) {
    const pool = Array.from({ length: 15 }, (_, i) => col * 15 + i + 1);
    const picked = shuffle(pool, rng).slice(0, 5);
    for (let row = 0; row < 5; row++) card[row * 5 + col] = picked[row];
  }
  card[CENTER] = 0;
  return card;
}
function newDrawOrder(rng) {
  return shuffle(Array.from({ length: BALLS }, (_, i) => i + 1), rng);
}
var LINES = [
  ...Array.from({ length: 5 }, (_, r) => [0, 1, 2, 3, 4].map((c) => r * 5 + c)),
  ...Array.from({ length: 5 }, (_, c) => [0, 1, 2, 3, 4].map((r) => r * 5 + c)),
  [0, 6, 12, 18, 24],
  [4, 8, 12, 16, 20]
];
var freshMarks = () => Array.from({ length: CELLS }, (_, i) => i === CENTER);
function completedLines(marks) {
  return LINES.filter((line) => line.every((i) => marks[i]));
}
var hasBingo = (marks) => completedLines(marks).length > 0;
function markable(card, marks, called) {
  const set = new Set(called);
  return card.filter((n, i) => n !== 0 && !marks[i] && set.has(n));
}

// src/games/bingo/engine/game.ts
function createBingo(config) {
  const n = config.seats.length;
  if (n < PLAYERS_MIN2 || n > PLAYERS_MAX2) throw new Error(`Bingo needs ${PLAYERS_MIN2}-${PLAYERS_MAX2} players`);
  if (new Set(config.seats.map((s) => s.id)).size !== n) throw new Error("Seat ids must be unique");
  const base = {
    version: 1,
    seed: config.seed >>> 0,
    rngState: config.seed >>> 0,
    round: 0,
    status: "playing",
    players: config.seats.map((s) => ({ ...s, card: [], marks: [] })),
    drawOrder: [],
    called: [],
    winners: [],
    claimBlockedUntil: {},
    scores: Object.fromEntries(config.seats.map((s) => [s.id, 0])),
    lastResult: null,
    turn: 0
  };
  return deal(base);
}
function deal(prev) {
  const rng = createRng(prev.rngState);
  const players = prev.players.map((p) => ({ ...p, card: generateCard(rng), marks: freshMarks() }));
  const drawOrder = newDrawOrder(rng);
  return { ...prev, rngState: rng.state(), round: prev.round + 1, status: "playing", players, drawOrder, called: [], winners: [], claimBlockedUntil: {}, lastResult: null };
}
function validateBingo(state, action) {
  switch (action.type) {
    case "CALL_NUMBER":
      if (state.status === "closing") return "closing";
      if (state.status !== "playing") return "not_playing";
      return state.called.length < BALLS ? null : "no_balls";
    case "CLOSE_ROUND":
      return state.status === "closing" || state.status === "playing" && state.called.length === BALLS ? null : "cannot_close";
  }
  const player = state.players.find((p) => p.id === action.playerId);
  if (!player) return "unknown_player";
  if (action.type === "NEXT_ROUND") return state.status === "round_over" ? null : "round_not_over";
  if (state.status === "round_over") return "not_playing";
  if (action.type === "MARK_NUMBER") {
    const i = player.card.indexOf(action.number);
    if (action.number === 0 || i < 0) return "not_on_card";
    if (!state.called.includes(action.number)) return "not_called";
    return player.marks[i] ? "already_marked" : null;
  }
  if (state.winners.includes(player.id)) return "already_claimed";
  return state.called.length < (state.claimBlockedUntil[player.id] ?? 0) ? "claim_blocked" : null;
}
function applyBingo(state, action) {
  const error = validateBingo(state, action);
  if (error) return { ok: false, error };
  const next = { ...state, turn: state.turn + 1 };
  switch (action.type) {
    case "CALL_NUMBER": {
      const number = state.drawOrder[state.called.length];
      const called = [...state.called, number];
      return { ok: true, state: { ...next, called }, events: [{ type: "called", number, count: called.length }] };
    }
    case "CLOSE_ROUND":
      return finish(next);
    case "NEXT_ROUND":
      return { ok: true, state: deal(next), events: [{ type: "dealt", round: state.round + 1 }] };
    case "MARK_NUMBER": {
      const players = state.players.map((p) => p.id === action.playerId ? { ...p, marks: p.marks.map((m, i) => m || p.card[i] === action.number) } : p);
      return { ok: true, state: { ...next, players }, events: [{ type: "marked", playerId: action.playerId, number: action.number }] };
    }
    case "CLAIM": {
      const player = state.players.find((p) => p.id === action.playerId);
      const valid = hasBingo(player.marks);
      const events = [{ type: "claimed", playerId: player.id, valid }];
      if (!valid) {
        return { ok: true, state: { ...next, claimBlockedUntil: { ...state.claimBlockedUntil, [player.id]: state.called.length + FALSE_CLAIM_PENALTY } }, events };
      }
      return { ok: true, state: { ...next, status: "closing", winners: [...state.winners, player.id] }, events };
    }
  }
}
function finish(state) {
  const winners = state.winners;
  const pointsEach = winners.length ? Math.floor(ROUND_POINTS / winners.length) : 0;
  const scores = { ...state.scores };
  for (const w of winners) scores[w] += pointsEach;
  const result = { round: state.round, winners: [...winners], atCall: winners.length ? state.called.length : 0, pointsEach };
  return { ok: true, state: { ...state, status: "round_over", scores, lastResult: result }, events: [{ type: "round_over", result }] };
}

// src/games/bingo/engine/parse.ts
var ID2 = /^[A-Za-z0-9_-]{1,32}$/;
function parseBingoAction(raw) {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return null;
  const r = raw;
  const keys = Object.keys(r).sort().join(",");
  switch (r.type) {
    case "CALL_NUMBER":
    case "CLOSE_ROUND":
      return keys === "type" ? { type: r.type } : null;
    case "MARK_NUMBER":
      if (keys !== "number,playerId,type" || typeof r.playerId !== "string" || !ID2.test(r.playerId)) return null;
      return Number.isInteger(r.number) && r.number >= 1 && r.number <= 75 ? { type: "MARK_NUMBER", playerId: r.playerId, number: r.number } : null;
    case "CLAIM":
    case "NEXT_ROUND":
      if (keys !== "playerId,type" || typeof r.playerId !== "string" || !ID2.test(r.playerId)) return null;
      return { type: r.type, playerId: r.playerId };
    default:
      return null;
  }
}

// src/games/bingo/engine/view.ts
function bingoView(state, me) {
  const self = state.players.find((p) => p.id === me);
  const card = self ? [...self.card] : [];
  const marks = self ? [...self.marks] : [];
  const open = state.status !== "round_over";
  return {
    me,
    card,
    marks,
    seats: state.players.map((p) => ({ id: p.id, name: p.name, kind: p.kind, daubs: p.marks.filter(Boolean).length - 1, score: state.scores[p.id] ?? 0, won: state.winners.includes(p.id) })),
    called: [...state.called],
    status: state.status,
    round: state.round,
    winners: [...state.winners],
    lastResult: state.lastResult ? { ...state.lastResult, winners: [...state.lastResult.winners] } : null,
    claimBlockedUntil: state.claimBlockedUntil[me] ?? 0,
    turn: state.turn,
    toMark: self && open ? markable(card, marks, state.called) : [],
    canClaim: !!self && open && !state.winners.includes(me) && hasBingo(marks)
  };
}

// src/games/domino/bots/dominoBot.ts
function endsAfter(view, tile, end) {
  if (view.line.length === 0) return [tile.a, tile.b];
  const left = view.line[0].left;
  const right = view.line[view.line.length - 1].right;
  if (end === "right") return [left, tile.a === right ? tile.b : tile.a];
  return [tile.a === left ? tile.b : tile.a, right];
}
function seenPerPip(view) {
  const seen = [0, 0, 0, 0, 0, 0, 0];
  const count = (t) => {
    seen[t.a]++;
    if (t.b !== t.a) seen[t.b]++;
  };
  view.line.forEach((p) => count(p.tile));
  view.hand.forEach(count);
  return seen;
}
function score(view, play, level) {
  const tile = view.hand.find((t) => t.id === play.tileId);
  const [l, r] = endsAfter(view, tile, play.end);
  let s = pipsOf(tile) + (isDouble(tile) ? 4 : 0);
  if (level === "normal") return s;
  const rest = view.hand.filter((t) => t.id !== tile.id);
  s += 2.5 * rest.filter((t) => fits(t, l) || fits(t, r)).length;
  const meIdx = view.seats.findIndex((x) => x.id === view.me);
  const next = view.seats[(meIdx + 1) % view.seats.length];
  if (next.lacks.includes(l)) s += 5;
  if (next.lacks.includes(r)) s += 5;
  const seen = seenPerPip(view);
  for (const pip of [l, r]) {
    const mine = rest.filter((t) => fits(t, pip)).length;
    if (seen[pip] >= 7) s += mine > 0 ? 3 : rest.length <= view.seats.reduce((m, x) => Math.min(m, x.tiles), 99) ? 4 : 1;
  }
  return s;
}
function decideDomino(view, difficulty, seed) {
  if (view.legal.length === 0) return null;
  const plays = view.legal.filter((a) => a.type === "PLAY_TILE");
  if (plays.length === 0) return view.legal[0];
  const rng = createRng(hashSeed(`${seed}|${view.me}|${view.round}|${view.turn}`));
  if (difficulty === "easy" || difficulty === "normal" && rng.next() < 0.2) return plays[Math.floor(rng.next() * plays.length)];
  let best = plays[0];
  let bestScore = -Infinity;
  for (const p of plays) {
    const s = score(view, p, difficulty) + rng.next() * 0.01;
    if (s > bestScore) {
      best = p;
      bestScore = s;
    }
  }
  return best;
}

// src/games/bingo/bots/bingoBot.ts
var PACE = {
  easy: { mark: [1300, 2600], claim: [1400, 2800], distracted: 0.3 },
  normal: { mark: [750, 1500], claim: [800, 1600], distracted: 0.12 },
  hard: { mark: [420, 850], claim: [380, 760], distracted: 0.03 }
};
function decideBingo(view, difficulty, seed) {
  if (view.status === "round_over") return null;
  const pace = PACE[difficulty];
  const rng = createRng(hashSeed(`${seed}|${view.me}|${view.round}|${view.called.length}|${view.toMark.join(",")}|${view.canClaim}`));
  const within = ([lo, hi]) => lo + rng.next() * (hi - lo);
  if (view.canClaim && view.called.length >= view.claimBlockedUntil) {
    return { action: { type: "CLAIM", playerId: view.me }, delayMs: within(pace.claim) };
  }
  if (view.toMark.length > 0) {
    const number = view.toMark[view.toMark.length - 1];
    const late = rng.next() < pace.distracted ? 1800 + rng.next() * 2200 : 0;
    return { action: { type: "MARK_NUMBER", playerId: view.me, number }, delayMs: within(pace.mark) + late };
  }
  return null;
}

// src/games/shared/multiplayer/roomCode.ts
var ROOM_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
var ROOM_CODE_RE = /^[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{5}$/;
function newRoomCode(random = cryptoIndex) {
  let code = "";
  for (let i = 0; i < 5; i++) code += ROOM_ALPHABET[random(ROOM_ALPHABET.length)];
  return code;
}
function cryptoIndex(n) {
  const buf = new Uint32Array(1);
  const limit = Math.floor(4294967296 / n) * n;
  do
    crypto.getRandomValues(buf);
  while (buf[0] >= limit);
  return buf[0] % n;
}

// src/games/shared/setup.ts
var DIFFICULTIES = ["easy", "normal", "hard"];
var BINGO_SPEEDS = ["slow", "normal", "fast"];

// src/games/online/server/handler.ts
var RoomStoreError = class extends Error {
  constructor(code) {
    super(code);
    this.code = code;
  }
};
var TIMING = {
  /** A human who doesn't move in this long has a sensible move played for them. */
  turnLimit: 45e3,
  /** Bingo: balls, per speed. */
  pace: { slow: 5200, normal: 3800, fast: 2600 },
  /** Bingo: other players may still share a BINGO for this long after the first. */
  claimWindow: 1600,
  /** Bingo: with all balls out and nobody claiming, close after this long. */
  allOut: 1e4,
  /** The next round starts by itself after this long (anyone may start it sooner). */
  nextRound: 12e3,
  /** First ball after the start. */
  firstBall: 2500
};
var fail = (code, detail) => ({ ok: false, code, detail });
function cleanName(raw) {
  if (typeof raw !== "string") return null;
  const name = [...raw].filter((ch) => ch.charCodeAt(0) >= 32 && ch.charCodeAt(0) !== 127 && ch !== "<" && ch !== ">").join("").trim().slice(0, 16);
  return name.length ? name : null;
}
function cleanSettings(game, raw) {
  const r = raw && typeof raw === "object" ? raw : {};
  if (!DIFFICULTIES.includes(r.difficulty)) return null;
  if (game === "domino") return r.target === 100 || r.target === 200 ? { difficulty: r.difficulty, target: r.target } : null;
  return BINGO_SPEEDS.includes(r.speed) ? { difficulty: r.difficulty, speed: r.speed } : null;
}
function parseRequest(raw) {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return null;
  const r = raw;
  const code = typeof r.code === "string" && ROOM_CODE_RE.test(r.code) ? r.code : null;
  switch (r.op) {
    case "create": {
      if (r.game !== "domino" && r.game !== "bingo") return null;
      const seats = r.seats;
      if (!Number.isInteger(seats) || seats < (r.game === "domino" ? 2 : 1) || seats > 4) return null;
      const name = cleanName(r.name);
      const settings = cleanSettings(r.game, r.settings);
      return name && settings ? { op: "create", game: r.game, seats, name, settings } : null;
    }
    case "join": {
      const name = cleanName(r.name);
      return code && name ? { op: "join", code, name } : null;
    }
    case "ready":
      return code && typeof r.ready === "boolean" ? { op: "ready", code, ready: r.ready } : null;
    case "act":
      return code && r.action && typeof r.action === "object" ? { op: "act", code, action: r.action } : null;
    case "start":
    case "tick":
    case "sync":
    case "leave":
    case "rematch":
      return code ? { op: r.op, code } : null;
    default:
      return null;
  }
}
var SEATS = ["s0", "s1", "s2", "s3"];
function sanitizeEvents(game, events, seat) {
  if (game === "domino") return events;
  return events.map((e) => e.type === "marked" && e.playerId !== seat ? { ...e, number: 0 } : e);
}
function viewFor(room, member, now, events = []) {
  const domino = room.game === "domino" && room.state ? dominoView(room.state, member.seat) : null;
  const bingo = room.game === "bingo" && room.state ? bingoView(room.state, member.seat) : null;
  let turnDeadline = null;
  if (domino && domino.status === "playing") {
    const cur = room.state.players[room.state.current];
    if (cur.kind !== "bot") turnDeadline = room.clock.lastAt + TIMING.turnLimit;
  }
  return {
    roomId: room.id,
    code: room.code,
    game: room.game,
    seats: room.seats,
    status: room.status,
    settings: room.settings,
    you: member.seat,
    members: room.members.map((m) => ({ seat: m.seat, name: m.name, ready: m.ready, host: m.userId === room.host })),
    version: room.version,
    serverNow: now,
    turnDeadline,
    domino,
    bingo,
    events: sanitizeEvents(room.game, events, member.seat)
  };
}
var viewsFor = (room, now, events) => room.members.map((m) => ({ userId: m.userId, view: viewFor(room, m, now, events) }));
function seedOf(room) {
  return room.state?.seed ?? 0;
}
function advance(room, now) {
  if (room.status !== "playing" || !room.state) return { room, events: [] };
  const events = [];
  let r = room;
  const set = (state, clock, ev) => {
    r = { ...r, state, clock: { ...r.clock, ...clock } };
    events.push(...ev);
  };
  if (r.game === "domino") {
    for (let guard = 0; guard < 60; guard++) {
      const s = r.state;
      if (s.status === "round_over") {
        if (now < r.clock.roundOverAt + TIMING.nextRound) break;
        const res2 = applyDomino(s, { type: "NEXT_ROUND", playerId: s.players[0].id });
        if (!res2.ok) break;
        set(res2.state, { lastAt: r.clock.roundOverAt + TIMING.nextRound }, res2.events);
        continue;
      }
      if (s.status !== "playing") break;
      const cur = s.players[s.current];
      const bot = cur.kind === "bot";
      const decision = decideDomino(dominoView(s, cur.id), bot ? r.settings.difficulty : "normal", seedOf(r) + s.current);
      if (!decision) break;
      const delay = bot ? decision.type === "PLAY_TILE" ? 900 : 520 : TIMING.turnLimit;
      const due = r.clock.lastAt + delay;
      if (now < due) break;
      const res = applyDomino(s, decision);
      if (!res.ok) break;
      const over = res.state.status !== "playing";
      set(res.state, { lastAt: due, ...over ? { roundOverAt: due } : {} }, res.events);
    }
    return { room: r, events };
  }
  const pace = TIMING.pace[r.settings.speed ?? "normal"] ?? TIMING.pace.normal;
  for (let guard = 0; guard < 400; guard++) {
    const s = r.state;
    if (s.status === "round_over") {
      if (now < r.clock.roundOverAt + TIMING.nextRound) break;
      const res2 = applyBingo(s, { type: "NEXT_ROUND", playerId: s.players[0].id });
      if (!res2.ok) break;
      set(res2.state, { lastCallAt: r.clock.roundOverAt + TIMING.nextRound - pace + TIMING.firstBall }, res2.events);
      continue;
    }
    if (s.status === "closing") {
      const due = r.clock.closingAt + TIMING.claimWindow;
      const bot2 = botBingoMove(r, s, due);
      if (bot2) {
        set(bot2.state, {}, bot2.events);
        continue;
      }
      if (now < due) break;
      const res2 = applyBingo(s, { type: "CLOSE_ROUND" });
      if (!res2.ok) break;
      set(res2.state, { roundOverAt: due }, res2.events);
      continue;
    }
    const bot = botBingoMove(r, s, now);
    if (bot) {
      set(bot.state, bot.state.status === "closing" ? { closingAt: bot.at } : {}, bot.events);
      continue;
    }
    if (s.called.length < 75) {
      const due = r.clock.lastCallAt + pace;
      if (now < due) break;
      const res2 = applyBingo(s, { type: "CALL_NUMBER" });
      if (!res2.ok) break;
      set(res2.state, { lastCallAt: now - due > pace ? now : due }, res2.events);
      continue;
    }
    if (now < r.clock.lastCallAt + TIMING.allOut) break;
    const res = applyBingo(s, { type: "CLOSE_ROUND" });
    if (!res.ok) break;
    set(res.state, { roundOverAt: now }, res.events);
  }
  return { room: r, events };
}
function botBingoMove(r, s, until) {
  for (let i = 0; i < s.players.length; i++) {
    const p = s.players[i];
    if (p.kind !== "bot") continue;
    const d = decideBingo(bingoView(s, p.id), r.settings.difficulty, seedOf(r) + i);
    if (!d) continue;
    const at = r.clock.lastCallAt + d.delayMs;
    if (at > until) continue;
    const res = applyBingo(s, d.action);
    if (res.ok) return { state: res.state, events: res.events, at };
  }
  return null;
}
function cryptoInt(n) {
  const buf = new Uint32Array(1);
  const limit = Math.floor(4294967296 / n) * n;
  do
    crypto.getRandomValues(buf);
  while (buf[0] >= limit);
  return buf[0] % n;
}
function newMatch(room, now, randomInt) {
  const seed = randomInt(65536) * 65536 + randomInt(65536) >>> 0;
  let bot = 0;
  const seats = SEATS.slice(0, room.seats).map((seat) => {
    const m = room.members.find((x) => x.seat === seat);
    return m ? { id: seat, name: m.name, kind: "human" } : { id: seat, name: `Bot ${++bot}`, kind: "bot" };
  });
  const state = room.game === "domino" ? createDomino({ seats, seed, targetScore: room.settings.target ?? 100 }) : createBingo({ seats, seed });
  const clock = { lastAt: now, lastCallAt: now - (TIMING.pace[room.settings.speed ?? "normal"] ?? 3800) + TIMING.firstBall, closingAt: 0, roundOverAt: 0 };
  return { ...room, status: "playing", state, clock };
}
async function handleRoomRequest(userId, body, deps) {
  if (!userId) return fail("unauthorized");
  if (deps.allow && !deps.allow(userId)) return fail("rate_limited");
  const req = parseRequest(body);
  if (!req) return fail("bad_request");
  const now = deps.now ?? Date.now;
  const randomInt = deps.randomInt ?? cryptoInt;
  if (req.op === "create") {
    for (let attempt = 0; attempt < 5; attempt++) {
      const code = newRoomCode(randomInt);
      const members = [{ userId, seat: "s0", name: req.name, ready: true }];
      try {
        const t = now();
        const room = await deps.store.insert({ code, game: req.game, seats: req.seats, host: userId, members, settings: req.settings }, (roomId) => [
          { userId, view: viewFor({ id: roomId, code, game: req.game, seats: req.seats, host: userId, status: "lobby", members, settings: req.settings, state: null, clock: { lastAt: t, lastCallAt: t, closingAt: 0, roundOverAt: 0 }, version: 1 }, members[0], t) }
        ]);
        return { ok: true, view: viewFor(room, members[0], t) };
      } catch (e) {
        if (!(e instanceof RoomStoreError && e.code === "conflict")) throw e;
      }
    }
    return fail("busy");
  }
  for (let attempt = 0; attempt < 4; attempt++) {
    const room = await deps.store.load(req.code);
    if (!room || room.status === "closed") return fail("not_found");
    const t = now();
    const me = room.members.find((m) => m.userId === userId);
    let next = room;
    let events = [];
    switch (req.op) {
      case "join": {
        if (me) return { ok: true, view: viewFor(room, me, t) };
        if (room.status !== "lobby") return fail("started");
        const seat = SEATS.slice(0, room.seats).find((s) => !room.members.some((m) => m.seat === s));
        if (!seat) return fail("full");
        next = { ...room, members: [...room.members, { userId, seat, name: req.name, ready: false }] };
        break;
      }
      case "ready":
        if (!me) return fail("not_member");
        if (room.status !== "lobby") return fail("started");
        next = { ...room, members: room.members.map((m) => m.userId === userId ? { ...m, ready: req.ready || m.userId === room.host } : m) };
        break;
      case "start":
        if (!me) return fail("not_member");
        if (room.host !== userId) return fail("not_host");
        if (room.status !== "lobby") return fail("started");
        if (!room.members.every((m) => m.ready)) return fail("not_ready");
        next = newMatch(room, t, randomInt);
        break;
      case "rematch": {
        if (!me) return fail("not_member");
        if (room.host !== userId) return fail("not_host");
        const over = room.state && (room.state.status === "game_over" || room.game === "bingo");
        if (room.status !== "playing" || !over) return fail("not_playing");
        if (room.game === "domino") {
          const seed = randomInt(65536) * 65536 + randomInt(65536) >>> 0;
          next = { ...room, state: rematch(room.state, seed), clock: { ...room.clock, lastAt: t } };
        } else next = newMatch(room, t, randomInt);
        break;
      }
      case "leave": {
        if (!me) return fail("not_member");
        const members = room.members.filter((m) => m.userId !== userId);
        if (room.status === "lobby") {
          next = { ...room, members, status: room.host === userId || members.length === 0 ? "closed" : "lobby" };
        } else {
          const state = room.state ? { ...room.state, players: room.state.players.map((p) => p.id === me.seat ? { ...p, kind: "bot" } : p) } : null;
          next = { ...room, members, state, status: members.length === 0 ? "closed" : room.status };
        }
        break;
      }
      case "act": {
        if (!me) return fail("not_member");
        if (room.status !== "playing" || !room.state) return fail("not_playing");
        const caught = advance(room, t);
        const action = room.game === "domino" ? parseDominoAction(req.action) : parseBingoAction(req.action);
        if (!action || !("playerId" in action)) return fail("forbidden");
        if (action.playerId !== me.seat) return fail("forbidden");
        const res = room.game === "domino" ? applyDomino(caught.room.state, action) : applyBingo(caught.room.state, action);
        if (!res.ok) {
          if (caught.events.length) {
            try {
              await deps.store.commit(caught.room, viewsFor({ ...caught.room, version: caught.room.version + 1 }, t, caught.events));
            } catch {
            }
          }
          return fail("rule", res.error);
        }
        const prev = caught.room.state;
        const clock = { lastAt: t };
        const status = res.state.status;
        if (room.game === "bingo" && prev.status === "playing" && status === "closing") clock.closingAt = t;
        if (status === "round_over" || status === "game_over") clock.roundOverAt = t;
        if (room.game === "bingo" && res.events.some((e) => e.type === "dealt")) clock.lastCallAt = t - (TIMING.pace[room.settings.speed ?? "normal"] ?? 3800) + TIMING.firstBall;
        next = { ...caught.room, state: res.state, clock: { ...caught.room.clock, ...clock } };
        events = [...caught.events, ...res.events];
        const after = advance(next, t);
        next = after.room;
        events.push(...after.events);
        break;
      }
      case "tick":
      case "sync": {
        if (!me) return fail("not_member");
        const after = advance(room, t);
        if (!after.events.length) return { ok: true, view: viewFor(room, me, t) };
        next = after.room;
        events = after.events;
        break;
      }
    }
    try {
      const version = await deps.store.commit(next, viewsFor({ ...next, version: next.version + 1 }, t, events));
      const committed = { ...next, version };
      const self = committed.members.find((m) => m.userId === userId);
      if (!self) return { ok: true, view: viewFor({ ...committed, status: "closed" }, me ?? { userId, seat: "s0", name: "", ready: false }, t) };
      return { ok: true, view: viewFor(committed, self, t, events) };
    } catch (e) {
      if (e instanceof RoomStoreError && e.code === "conflict") continue;
      throw e;
    }
  }
  return fail("busy");
}

// supabase/functions/_shared/roomStore.ts
function postgrestRoomStore(supabaseUrl, serviceKey, fetchImpl = fetch) {
  async function rpc(fn, args) {
    const res = await fetchImpl(`${supabaseUrl}/rest/v1/rpc/${fn}`, {
      method: "POST",
      headers: { "content-type": "application/json", apikey: serviceKey, authorization: `Bearer ${serviceKey}` },
      body: JSON.stringify(args)
    });
    const body = await res.json().catch(() => null);
    if (!res.ok) {
      const code = body?.code;
      if (code === "P0409") throw new RoomStoreError("conflict");
      if (code === "P0400") throw new RoomStoreError("invalid");
      throw new Error(`rpc ${fn} failed: ${res.status} ${code ?? ""}`);
    }
    return body;
  }
  const views = (out) => out.map((v) => ({ userId: v.userId, view: v.view }));
  return {
    async insert(room, makeViews) {
      const id = await rpc("room_insert", {
        p_code: room.code,
        p_game: room.game,
        p_seats: room.seats,
        p_host: room.host,
        p_members: room.members,
        p_settings: room.settings,
        p_views: views(makeViews("pending"))
      });
      return { ...room, id, status: "lobby", state: null, clock: { lastAt: 0, lastCallAt: 0, closingAt: 0, roundOverAt: 0 }, version: 1 };
    },
    async load(code) {
      const row = await rpc("room_load", { p_code: code });
      if (!row) return null;
      return {
        id: row.id,
        code: row.code,
        game: row.game,
        seats: row.seats,
        host: row.host,
        status: row.status,
        members: row.members,
        settings: row.settings,
        state: row.state ?? null,
        clock: { lastAt: 0, lastCallAt: 0, closingAt: 0, roundOverAt: 0, ...row.clock },
        version: row.version
      };
    },
    async commit(room, out) {
      return rpc("room_commit", {
        p_id: room.id,
        p_version: room.version,
        p_status: room.status,
        p_members: room.members,
        p_state: room.state,
        p_clock: room.clock,
        p_views: views(out)
      });
    }
  };
}

// supabase/functions/game-room/source.ts
var SUPABASE_URL = Deno.env.get("SUPABASE_URL");
var ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY");
var SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
var ALLOWED = /* @__PURE__ */ new Set(["https://siiknotic.github.io", "http://localhost:5173", "http://127.0.0.1:5173", "http://localhost:4173"]);
var store = postgrestRoomStore(SUPABASE_URL, SERVICE_KEY);
var hits = /* @__PURE__ */ new Map();
function allow(userId) {
  const now = Date.now();
  const recent = (hits.get(userId) ?? []).filter((t) => now - t < 1e3);
  recent.push(now);
  hits.set(userId, recent);
  if (hits.size > 1e4) hits.clear();
  return recent.length <= 12;
}
async function verifiedUser(req) {
  const auth = req.headers.get("authorization") ?? "";
  if (!auth.startsWith("Bearer ")) return null;
  const res = await fetch(`${SUPABASE_URL}/auth/v1/user`, { headers: { apikey: ANON_KEY, authorization: auth } });
  if (!res.ok) return null;
  const user = await res.json().catch(() => null);
  return typeof user?.id === "string" ? user.id : null;
}
Deno.serve(async (req) => {
  const origin = req.headers.get("origin") ?? "";
  const cors = {
    "access-control-allow-origin": ALLOWED.has(origin) ? origin : "https://siiknotic.github.io",
    "access-control-allow-headers": "authorization, apikey, content-type, x-client-info",
    "access-control-allow-methods": "POST, OPTIONS",
    vary: "origin"
  };
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
  if (req.method !== "POST") return Response.json({ ok: false, code: "bad_request" }, { status: 405, headers: cors });
  const text = await req.text();
  if (text.length > 2048) return Response.json({ ok: false, code: "bad_request" }, { status: 413, headers: cors });
  let body = null;
  try {
    body = JSON.parse(text);
  } catch {
    return Response.json({ ok: false, code: "bad_request" }, { status: 400, headers: cors });
  }
  try {
    const out = await handleRoomRequest(await verifiedUser(req), body, { store, allow });
    const status = out.ok ? 200 : out.code === "unauthorized" ? 401 : out.code === "rate_limited" ? 429 : out.code === "not_found" ? 404 : 400;
    return Response.json(out, { status, headers: { ...cors, "cache-control": "no-store" } });
  } catch (e) {
    console.error("game-room", e instanceof Error ? e.message : e);
    return Response.json({ ok: false, code: "busy" }, { status: 503, headers: cors });
  }
});
