// GENERATED by scripts/slot-stats.ts from machines.ts. Do not edit by hand.
// rtp: exact expected return; hitRate, sd (volatility), featureRate, bigWinRate: simulated over `rounds`.
import type { MachineId } from './engine';

export interface MachineStats {
  rtp: number;
  hitRate: number;
  sd: number;
  featureRate: number;
  bigWinRate: number;
  maxWin: number;
  lines: number;
  rounds: number;
}

export const MACHINE_STATS: Record<MachineId, MachineStats> = {
  lucky7s: { rtp: 0.9561, hitRate: 0.314, sd: 3.23, featureRate: 0, bigWinRate: 0.01215, maxWin: 1000, lines: 5, rounds: 2000000 },
  diamondRoyale: { rtp: 0.9572, hitRate: 0.2338, sd: 5.3, featureRate: 0, bigWinRate: 0.01931, maxWin: 2500, lines: 10, rounds: 2000000 },
  goldenFortune: { rtp: 0.9519, hitRate: 0.2371, sd: 4, featureRate: 0.0039, bigWinRate: 0.02296, maxWin: 3000, lines: 20, rounds: 2000000 },
  inferno: { rtp: 0.9518, hitRate: 0.2658, sd: 9.7, featureRate: 0.0073, bigWinRate: 0.01873, maxWin: 5000, lines: 20, rounds: 2000000 },
  tropical: { rtp: 0.9635, hitRate: 0.2537, sd: 3.31, featureRate: 0.00559, bigWinRate: 0.01796, maxWin: 1500, lines: 15, rounds: 2000000 },
  pirates: { rtp: 0.9566, hitRate: 0.2456, sd: 5.77, featureRate: 0.00942, bigWinRate: 0.01677, maxWin: 3500, lines: 20, rounds: 2000000 },
  cosmic: { rtp: 0.9452, hitRate: 0.2777, sd: 6.92, featureRate: 0.00566, bigWinRate: 0.02039, maxWin: 5000, lines: 25, rounds: 2000000 },
  royal: { rtp: 0.9541, hitRate: 0.205, sd: 4.11, featureRate: 0.00345, bigWinRate: 0.01903, maxWin: 2000, lines: 10, rounds: 2000000 },
};
