# Builds every app icon and splash screen from the Carta Casino logo (branding/carta-logo.webp, a framed
# rounded square on black, generated by the project owner):
#   python3 scripts/brand-icons.py
#
# - Web: favicons (32, 192 px, transparent corners), apple-touch-icon (180 px, opaque) and a 512 px
#   store-style icon (opaque).
# - Android: legacy and round launcher icons per density, the adaptive icon foreground (the whole logo in
#   the 72 dp visible area of the 108 dp layer, so no launcher mask cuts the name) over a near-black
#   background colour, and the splash screens (the logo centred on a dark, warm glow).
import os

from PIL import Image, ImageDraw

SRC = 'branding/carta-logo.webp'
RES = 'android/app/src/main/res/'
RADIUS = 0.196  # the logo's corner radius, as a fraction of its side
BACKGROUND = (8, 5, 4)  # keep in sync with values/ic_launcher_background.xml
DENSITIES = {'mdpi': 1, 'hdpi': 1.5, 'xhdpi': 2, 'xxhdpi': 3, 'xxxhdpi': 4}


def mask(size, shape):
    big = size * 4
    m = Image.new('L', (big, big), 0)
    d = ImageDraw.Draw(m)
    if shape == 'round':
        d.ellipse((0, 0, big - 1, big - 1), fill=255)
    else:
        d.rounded_rectangle((0, 0, big - 1, big - 1), radius=round(big * RADIUS), fill=255)
    return m.resize((size, size), Image.LANCZOS)


def logo(size, shape='rounded'):
    im = SRC_IMG.resize((size, size), Image.LANCZOS).convert('RGBA')
    im.putalpha(mask(size, shape))
    return im


def opaque(size):
    out = Image.new('RGB', (size, size), BACKGROUND)
    out.paste(logo(size), (0, 0), logo(size))
    return out


def splash(w, h):
    out = Image.new('RGB', (w, h), BACKGROUND)
    glow = Image.new('L', (w, h), 0)
    r = int(min(w, h) * 0.62)
    ImageDraw.Draw(glow).ellipse((w // 2 - r, h // 2 - r, w // 2 + r, h // 2 + r), fill=255)
    from PIL import ImageFilter

    glow = glow.filter(ImageFilter.GaussianBlur(r * 0.45))
    out.paste(Image.new('RGB', (w, h), (58, 30, 10)), (0, 0), glow.point(lambda v: v * 0.55))
    side = int(min(w, h) * (0.46 if h >= w else 0.52))
    mark = logo(side)
    out.paste(mark, ((w - side) // 2, (h - side) // 2), mark)
    return out


def save_png(im, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    im.save(path, 'PNG', optimize=False)


SRC_IMG = Image.open(SRC).convert('RGB')

save_png(logo(32), 'public/icons/icon-32.png')
save_png(logo(192), 'public/icons/icon-192.png')
save_png(opaque(180), 'public/icons/icon-180.png')
save_png(opaque(512), 'public/icons/icon-512.png')

for name, k in DENSITIES.items():
    save_png(logo(round(48 * k)), f'{RES}mipmap-{name}/ic_launcher.png')
    save_png(logo(round(48 * k), 'round'), f'{RES}mipmap-{name}/ic_launcher_round.png')
    layer = round(108 * k)
    fg = Image.new('RGBA', (layer, layer), (0, 0, 0, 0))
    mark = logo(round(72 * k))
    fg.paste(mark, ((layer - mark.width) // 2, (layer - mark.height) // 2), mark)
    save_png(fg, f'{RES}mipmap-{name}/ic_launcher_foreground.png')

for folder in sorted(os.listdir(RES)):
    path = f'{RES}{folder}/splash.png'
    if os.path.exists(path):
        w, h = Image.open(path).size
        save_png(splash(w, h), path)
