// Regenerates src/casino/premium/machineStats.ts from the machine configs:
//   npm run slots:stats   (from the repository root)
// RTP is exact (computed from the reel strips); hit rate and volatility are simulated.
import { writeFileSync } from 'node:fs';
import { MACHINES } from '../src/casino/premium/machines';
import { exactReturn, simulate } from '../src/casino/premium/analysis';

const ROUNDS = 2_000_000;
const rows = Object.values(MACHINES).map((m) => {
  const e = exactReturn(m);
  const s = simulate(m, ROUNDS, 20260924);
  const r = (x: number, d = 4) => Number(x.toFixed(d));
  return `  ${m.id}: { rtp: ${r(e.rtp)}, hitRate: ${r(s.hitRate)}, sd: ${r(s.sd, 2)}, featureRate: ${r(s.featureRate, 5)}, bigWinRate: ${r(s.bigWinRate, 5)}, maxWin: ${m.maxWin}, lines: ${m.lines.length}, rounds: ${ROUNDS} },`;
});
writeFileSync(
  'src/casino/premium/machineStats.ts',
  `// GENERATED by scripts/slot-stats.ts from machines.ts. Do not edit by hand.
// rtp: exact expected return; hitRate, sd (volatility), featureRate, bigWinRate: simulated over \`rounds\`.
import type { MachineId } from './engine';

export interface MachineStats {
  rtp: number;
  hitRate: number;
  sd: number;
  featureRate: number;
  bigWinRate: number;
  maxWin: number;
  lines: number;
  rounds: number;
}

export const MACHINE_STATS: Record<MachineId, MachineStats> = {
${rows.join('\n')}
};
`
);
console.log(rows.join('\n'));
