// @ts-nocheck -- generated by npm run functions:build from source.ts; do not edit

// src/casino/premium/engine.ts
var MACHINE_IDS = ["lucky7s", "diamondRoyale", "goldenFortune", "inferno", "tropical", "pirates", "cosmic", "royal"];
var isMachineId = (x) => typeof x === "string" && MACHINE_IDS.includes(x);
var REELS = 5;
function buildStrip(counts) {
  const entries = Object.entries(counts).filter(([, n]) => n > 0);
  const total = entries.reduce((s, [, n]) => s + n, 0);
  const slots = [];
  entries.forEach(([s, n], i) => {
    for (let k = 0; k < n; k++) slots.push({ s, at: (k + 0.5) * total / n + i * 0.013 });
  });
  slots.sort((a, b) => a.at - b.at);
  const strip = slots.map((x) => x.s);
  for (let pass = 0; pass < 3; pass++) {
    for (let i = 0; i < strip.length; i++) {
      const j = (i + 1) % strip.length;
      if (strip[i] !== strip[j]) continue;
      for (let k = 2; k < strip.length; k++) {
        const m = (i + k) % strip.length;
        const prev = strip[(m - 1 + strip.length) % strip.length];
        const next = strip[(m + 1) % strip.length];
        if (strip[m] !== strip[i] && prev !== strip[i] && next !== strip[i] && strip[(i - 1 + strip.length) % strip.length] !== strip[m]) {
          [strip[j], strip[m]] = [strip[m], strip[j]];
          break;
        }
      }
    }
  }
  return strip;
}
var stripCache = /* @__PURE__ */ new WeakMap();
function stripsOf(m) {
  let s = stripCache.get(m);
  if (!s) {
    s = Array.from({ length: REELS }, (_, r) => buildStrip(Object.fromEntries(Object.entries(m.reelCounts).map(([sym, c]) => [sym, c[r]]))));
    stripCache.set(m, s);
  }
  return s;
}
var mod = (x, n) => (x % n + n) % n;
var symbolOn = (strip, stop, offset = 0) => strip[mod(stop + offset, strip.length)];
function gridOf(m, stops) {
  const strips = stripsOf(m);
  return stops.map((stop, r) => [symbolOn(strips[r], stop, -1), symbolOn(strips[r], stop), symbolOn(strips[r], stop, 1)]);
}
function cryptoUint32() {
  const buf = new Uint32Array(1);
  globalThis.crypto.getRandomValues(buf);
  return buf[0];
}
function uniform(n, rand) {
  const limit = Math.floor(4294967296 / n) * n;
  for (; ; ) {
    const x = rand() >>> 0;
    if (x < limit) return x % n;
  }
}
function weighted(w, rand) {
  const total = w.weights.reduce((a, b) => a + b, 0);
  let x = uniform(total, rand);
  for (let i = 0; i < w.values.length; i++) {
    if (x < w.weights[i]) return w.values[i];
    x -= w.weights[i];
  }
  return w.values[w.values.length - 1];
}
function lineResult(m, syms) {
  const wild = Object.keys(m.symbols).find((s) => m.symbols[s].kind === "wild");
  const isWild2 = (s) => s === wild;
  const base = syms.find((s) => !isWild2(s)) ?? wild;
  let count = 0;
  while (count < syms.length && (syms[count] === base || isWild2(syms[count])) && m.symbols[syms[count]].kind !== "scatter") count++;
  let wilds = 0;
  while (wilds < syms.length && isWild2(syms[wilds])) wilds++;
  const basePays = m.symbols[base]?.kind === "regular" && count >= 3 ? m.symbols[base].pays?.[count - 3] ?? 0 : 0;
  const wildPays = wild && wilds >= 3 ? m.symbols[wild].pays?.[wilds - 3] ?? 0 : 0;
  if (!basePays && !wildPays) return null;
  if (wildPays > basePays) return { symbol: wild, count: wilds, pays: wildPays, usesWild: true };
  return { symbol: base, count, pays: basePays, usesWild: syms.slice(0, count).some(isWild2) };
}
function evaluateSpin(m, draw2, bet, freeMult = 1) {
  const lineBet = bet / m.lines.length;
  const grid = gridOf(m, draw2.stops);
  const wild = Object.keys(m.symbols).find((s) => m.symbols[s].kind === "wild");
  const scatter = Object.keys(m.symbols).find((s) => m.symbols[s].kind === "scatter");
  const expanded = (m.features.expandingWild ?? []).filter((r) => wild && grid[r].includes(wild));
  const play = grid.map((col, r) => expanded.includes(r) ? col.map(() => wild) : col);
  const wildMult = draw2.wildMult ?? 1;
  const lines2 = [];
  m.lines.forEach((rows, line) => {
    const res = lineResult(m, rows.map((row, reel) => play[reel][row]));
    if (!res) return;
    const multiplier = res.usesWild ? wildMult : 1;
    lines2.push({ line, symbol: res.symbol, count: res.count, pays: res.pays, multiplier, amount: res.pays * lineBet * multiplier });
  });
  const scatters = scatter ? grid.flat().filter((s) => s === scatter).length : 0;
  const sp = m.features.scatterPays;
  const scatterWin = sp && scatters >= 3 ? sp[Math.min(scatters, 5) - 3] * bet : 0;
  const winMult = draw2.winMult ?? 1;
  const raw = lines2.reduce((s, l) => s + l.amount, 0) + scatterWin;
  const payout = Math.floor(raw * winMult * freeMult);
  return { stops: [...draw2.stops], grid, expanded, lines: lines2, scatters, scatterWin, wildMult, winMult, freeMult, payout };
}
var freeCount = (m, scatters) => {
  const fs = m.features.freeSpins;
  return fs && scatters >= 3 ? fs.count[Math.min(scatters, 5) - 3] : 0;
};
function tierFor(payout, bet, jackpot) {
  if (jackpot) return "jackpot";
  if (payout <= 0) return "none";
  if (payout <= bet) return "tiny";
  if (payout < bet * 10) return "small";
  if (payout < bet * 40) return "big";
  return "mega";
}
function playRound(m, bet, rand = cryptoUint32) {
  if (!isValidBetFor(m, bet)) throw new Error("invalid bet");
  const strips = stripsOf(m);
  const wild = Object.keys(m.symbols).find((s) => m.symbols[s].kind === "wild");
  const drawSpin = () => {
    const stops = strips.map((s) => uniform(s.length, rand));
    const draw2 = { stops };
    const wm = m.features.wildMultiplier;
    if (wm && wild && gridOf(m, stops).some((c) => c.includes(wild))) draw2.wildMult = weighted(wm, rand);
    const xm = m.features.winMultiplier;
    if (xm && evaluateSpin(m, draw2, bet).payout > 0 && uniform(1e3, rand) < xm.chance) draw2.winMult = weighted(xm, rand);
    return draw2;
  };
  const draws = { base: drawSpin(), free: [], picks: [] };
  const base = evaluateSpin(m, draws.base, bet);
  let left = freeCount(m, base.scatters);
  const fs = m.features.freeSpins;
  while (fs && left > 0 && draws.free.length < fs.max) {
    const d = drawSpin();
    draws.free.push(d);
    left--;
    if (fs.retrigger) left += freeCount(m, evaluateSpin(m, d, bet).scatters);
  }
  const pb = m.features.pickBonus;
  if (pb && base.scatters >= 3) for (let i = 0; i < pb.picks[Math.min(base.scatters, 5) - 3]; i++) draws.picks.push(weighted(pb, rand));
  return settleRound(m, bet, draws);
}
function settleRound(m, bet, draws) {
  if (!isValidBetFor(m, bet) || !isValidDraws(m, draws)) throw new Error("invalid round");
  const fs = m.features.freeSpins;
  const base = evaluateSpin(m, draws.base, bet);
  checkMultipliers(m, draws.base, base, bet);
  let expected = freeCount(m, base.scatters);
  const free = [];
  let mult = fs?.multiplier ?? 1;
  for (let i = 0; i < draws.free.length; i++) {
    if (i >= expected) throw new Error("too many free spins");
    const r = evaluateSpin(m, draws.free[i], bet, mult);
    checkMultipliers(m, draws.free[i], r, bet);
    free.push(r);
    if (fs?.retrigger) expected += freeCount(m, r.scatters);
    mult += fs?.step ?? 0;
  }
  if (draws.free.length !== Math.min(expected, fs?.max ?? 0)) throw new Error("missing free spins");
  const pb = m.features.pickBonus;
  const expectedPicks = pb && base.scatters >= 3 ? pb.picks[Math.min(base.scatters, 5) - 3] : 0;
  if (draws.picks.length !== expectedPicks || draws.picks.some((v) => !pb.values.includes(v))) throw new Error("bad picks");
  const pickWin = draws.picks.reduce((s, v) => s + v, 0) * bet;
  const jl = m.features.jackpotLadder;
  const jackpot = jl && base.scatters >= 3 ? ["minor", "major", "grand"][Math.min(base.scatters, 5) - 3] : null;
  const jackpotWin = jackpot && jl ? jl.tiers[["minor", "major", "grand"].indexOf(jackpot)] * bet : 0;
  const topLine = [base, ...free].some((s) => s.lines.some((l) => l.symbol === m.top && l.count === 5));
  const raw = base.payout + free.reduce((s, f) => s + f.payout, 0) + pickWin + jackpotWin;
  const cap = m.maxWin * bet;
  const payout = Math.min(raw, cap);
  const isJackpot = topLine || jackpot === "major" || jackpot === "grand";
  return {
    draws,
    base,
    free,
    freeAwarded: draws.free.length,
    picks: [...draws.picks],
    pickWin,
    jackpot,
    jackpotWin,
    topLine,
    raw,
    payout,
    capped: raw > cap,
    tier: tierFor(payout, bet, isJackpot)
  };
}
function checkMultipliers(m, d, r, bet) {
  const wild = Object.keys(m.symbols).find((s) => m.symbols[s].kind === "wild");
  const wm = m.features.wildMultiplier;
  const wildVisible = !!wild && r.grid.some((c) => c.includes(wild));
  if (d.wildMult !== void 0 && (!wm || !wildVisible || !wm.values.includes(d.wildMult))) throw new Error("bad wild multiplier");
  if (wm && wildVisible && d.wildMult === void 0) throw new Error("missing wild multiplier");
  const xm = m.features.winMultiplier;
  if (d.winMult !== void 0) {
    const plain = evaluateSpin(m, { stops: d.stops, wildMult: d.wildMult }, bet);
    if (!xm || plain.payout <= 0 || !xm.values.includes(d.winMult)) throw new Error("bad win multiplier");
  }
}
var isValidBetFor = (m, bet) => typeof bet === "number" && m.betLevels.includes(bet);
function isValidStopsFor(m, stops) {
  const strips = stripsOf(m);
  return Array.isArray(stops) && stops.length === REELS && stops.every((s, r) => Number.isInteger(s) && s >= 0 && s < strips[r].length);
}
function isValidSpinDraw(m, d) {
  if (!d || typeof d !== "object") return false;
  const x = d;
  const num = (v) => v === void 0 || typeof v === "number" && Number.isFinite(v);
  const keys = Object.keys(x).every((k) => k === "stops" || k === "wildMult" || k === "winMult");
  return keys && isValidStopsFor(m, x.stops) && num(x.wildMult) && num(x.winMult);
}
function isValidDraws(m, d) {
  if (!d || typeof d !== "object") return false;
  const x = d;
  return isValidSpinDraw(m, x.base) && Array.isArray(x.free) && x.free.length <= 500 && x.free.every((f) => isValidSpinDraw(m, f)) && Array.isArray(x.picks) && x.picks.length <= 10 && x.picks.every((p) => typeof p === "number" && Number.isFinite(p));
}
var REQUEST_ID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var isRequestId = (x) => typeof x === "string" && REQUEST_ID_RE.test(x);

// src/casino/premium/machines.ts
var ALL_LINES = [
  [1, 1, 1, 1, 1],
  [0, 0, 0, 0, 0],
  [2, 2, 2, 2, 2],
  [0, 1, 2, 1, 0],
  [2, 1, 0, 1, 2],
  [0, 0, 1, 2, 2],
  [2, 2, 1, 0, 0],
  [1, 0, 0, 0, 1],
  [1, 2, 2, 2, 1],
  [1, 2, 1, 0, 1],
  [1, 0, 1, 2, 1],
  [0, 1, 1, 1, 0],
  [2, 1, 1, 1, 2],
  [0, 1, 0, 1, 0],
  [2, 1, 2, 1, 2],
  [1, 1, 0, 1, 1],
  [1, 1, 2, 1, 1],
  [0, 0, 2, 0, 0],
  [2, 2, 0, 2, 2],
  [0, 2, 2, 2, 0],
  [2, 0, 0, 0, 2],
  [1, 0, 2, 0, 1],
  [1, 2, 0, 2, 1],
  [0, 2, 0, 2, 0],
  [2, 0, 2, 0, 2]
];
var lines = (n) => ALL_LINES.slice(0, n);
var levels = (lineCount, coins) => coins.map((c) => c * lineCount);
var reg = (a, b, c) => ({ kind: "regular", pays: [a, b, c] });
var MACHINES = {
  // Classic Vegas stepper: 22-stop reels, a Wild 7, frequent small pays, bells pay anywhere.
  lucky7s: {
    id: "lucky7s",
    lines: lines(5),
    betLevels: levels(5, [2, 4, 10, 20, 40, 100, 200]),
    top: "seven",
    volatility: "low",
    maxWin: 1e3,
    symbols: {
      seven: reg(75, 375, 2e3),
      bar3: reg(40, 150, 600),
      bar2: reg(25, 75, 275),
      bar: reg(15, 45, 150),
      coin: reg(8, 25, 95),
      cherry: reg(6, 15, 45),
      lemon: reg(4, 10, 40),
      wild7: { kind: "wild", pays: [75, 375, 2e3] },
      bell: { kind: "scatter" }
    },
    // 22 stops per reel, like a mechanical reel.
    reelCounts: {
      seven: [1, 1, 1, 1, 1],
      bar3: [1, 1, 1, 1, 1],
      bar2: [2, 2, 2, 2, 2],
      bar: [2, 2, 2, 2, 2],
      coin: [3, 3, 3, 3, 3],
      cherry: [7, 7, 7, 7, 7],
      lemon: [6, 6, 6, 6, 6],
      wild7: [1, 1, 1, 1, 1],
      bell: [1, 1, 1, 1, 1]
    },
    features: { scatterPays: [2, 10, 50] }
  },
  // Fewer small wins; the crystal wild appears only on reels 2–4 and fills its reel.
  diamondRoyale: {
    id: "diamondRoyale",
    lines: lines(10),
    betLevels: levels(10, [1, 2, 5, 10, 20, 50, 100]),
    top: "diamond",
    volatility: "medium",
    maxWin: 2500,
    symbols: {
      diamond: reg(80, 400, 2200),
      crown: reg(45, 175, 900),
      ruby: reg(30, 125, 450),
      sapphire: reg(25, 90, 300),
      emerald: reg(20, 60, 225),
      ring: reg(15, 45, 150),
      A: reg(9, 25, 90),
      K: reg(9, 20, 80),
      Q: reg(7, 15, 60),
      J: reg(7, 15, 60),
      crystal: { kind: "wild" }
    },
    reelCounts: {
      diamond: [2, 2, 2, 2, 2],
      crown: [3, 3, 3, 3, 3],
      ruby: [3, 3, 3, 3, 3],
      sapphire: [4, 4, 4, 4, 4],
      emerald: [4, 4, 4, 4, 4],
      ring: [5, 5, 5, 5, 5],
      A: [8, 8, 8, 8, 8],
      K: [8, 8, 8, 8, 8],
      Q: [8, 8, 8, 8, 8],
      J: [8, 8, 8, 8, 8],
      crystal: [0, 2, 2, 2, 0]
    },
    features: { expandingWild: [1, 2, 3] }
  },
  // Coins pay anywhere and open the Coin Vault pick bonus.
  goldenFortune: {
    id: "goldenFortune",
    lines: lines(20),
    betLevels: levels(20, [1, 2, 5, 10, 20, 50, 100]),
    top: "idol",
    volatility: "medium-high",
    maxWin: 3e3,
    symbols: {
      idol: reg(225, 1400, 7100),
      ingot: reg(150, 550, 2300),
      scarab: reg(95, 375, 1400),
      sundisk: reg(70, 225, 950),
      hourglass: reg(45, 175, 725),
      A: reg(25, 70, 350),
      K: reg(25, 55, 275),
      Q: reg(20, 45, 225),
      J: reg(15, 35, 175),
      T: reg(15, 35, 175),
      mask: { kind: "wild", pays: [225, 1400, 7100] },
      coin: { kind: "scatter" }
    },
    reelCounts: {
      idol: [2, 2, 2, 2, 2],
      ingot: [3, 3, 3, 3, 3],
      scarab: [3, 3, 3, 3, 3],
      sundisk: [4, 4, 4, 4, 4],
      hourglass: [4, 4, 4, 4, 4],
      A: [5, 5, 5, 5, 5],
      K: [5, 5, 5, 5, 5],
      Q: [6, 6, 6, 6, 6],
      J: [6, 6, 6, 6, 6],
      T: [6, 6, 6, 6, 6],
      mask: [1, 1, 1, 1, 1],
      coin: [1, 1, 2, 1, 1]
    },
    features: {
      scatterPays: [2, 5, 20],
      pickBonus: { kind: "coins", picks: [4, 5, 6], values: [1, 2, 3, 5, 10, 25], weights: [30, 25, 20, 14, 8, 3] }
    }
  },
  // Rare, heavy hits: fire wilds multiply the line, free spins raise the multiplier every spin.
  inferno: {
    id: "inferno",
    lines: lines(20),
    betLevels: levels(20, [1, 2, 5, 10, 20, 50, 100]),
    top: "dragon",
    volatility: "high",
    maxWin: 5e3,
    symbols: {
      dragon: reg(175, 925, 3800),
      phoenix: reg(75, 375, 1500),
      skull: reg(35, 175, 575),
      lava: reg(25, 70, 225),
      A: reg(3, 9, 45),
      K: reg(3, 9, 35),
      Q: reg(2, 7, 35),
      J: reg(2, 7, 35),
      T: reg(2, 7, 25),
      fire: { kind: "wild" },
      volcano: { kind: "scatter" }
    },
    reelCounts: {
      dragon: [1, 1, 1, 1, 1],
      phoenix: [2, 2, 2, 2, 2],
      skull: [3, 3, 3, 3, 3],
      lava: [4, 4, 4, 4, 4],
      A: [4, 4, 4, 4, 4],
      K: [4, 4, 4, 4, 4],
      Q: [4, 4, 4, 4, 4],
      J: [4, 4, 4, 4, 4],
      T: [4, 4, 4, 4, 4],
      fire: [0, 1, 1, 1, 0],
      volcano: [1, 1, 1, 1, 1]
    },
    features: {
      scatterPays: [2, 10, 50],
      wildMultiplier: { values: [2, 3, 5, 10], weights: [50, 30, 15, 5] },
      freeSpins: { count: [8, 12, 16], multiplier: 1, step: 1, retrigger: false, max: 16 }
    }
  },
  // Plenty of small wins; the island opens free spins where every win pays double.
  tropical: {
    id: "tropical",
    lines: lines(15),
    betLevels: levels(15, [1, 2, 5, 10, 20, 50, 100]),
    top: "parrot",
    volatility: "medium",
    maxWin: 1500,
    symbols: {
      parrot: reg(175, 725, 2900),
      sailboat: reg(125, 400, 1500),
      fish: reg(75, 250, 950),
      shell: reg(60, 175, 725),
      hibiscus: reg(50, 125, 475),
      banana: reg(25, 65, 200),
      citrus: reg(20, 50, 150),
      grape: reg(15, 40, 150),
      cherry: reg(15, 30, 100),
      palm: { kind: "wild", pays: [175, 725, 2900] },
      island: { kind: "scatter" }
    },
    reelCounts: {
      parrot: [2, 2, 2, 2, 2],
      sailboat: [3, 3, 3, 3, 3],
      fish: [4, 4, 4, 4, 4],
      shell: [4, 4, 4, 4, 4],
      hibiscus: [5, 5, 5, 5, 5],
      banana: [8, 8, 8, 8, 8],
      citrus: [8, 8, 8, 8, 8],
      grape: [9, 9, 9, 9, 9],
      cherry: [9, 9, 9, 9, 9],
      palm: [1, 1, 1, 1, 1],
      island: [2, 1, 2, 1, 2]
    },
    features: {
      scatterPays: [1, 5, 20],
      freeSpins: { count: [10, 15, 20], multiplier: 2, retrigger: true, max: 50 }
    }
  },
  // Treasure chests open the chest bonus; big symbol pays.
  pirates: {
    id: "pirates",
    lines: lines(20),
    betLevels: levels(20, [1, 2, 5, 10, 20, 50, 100]),
    top: "captain",
    volatility: "medium-high",
    maxWin: 3500,
    symbols: {
      captain: reg(175, 800, 5300),
      ship: reg(100, 400, 1600),
      compass: reg(65, 225, 800),
      anchor: reg(35, 125, 525),
      map: reg(25, 100, 400),
      A: reg(10, 35, 175),
      K: reg(10, 30, 150),
      Q: reg(10, 25, 125),
      J: reg(9, 20, 100),
      T: reg(9, 20, 100),
      flag: { kind: "wild", pays: [175, 800, 5300] },
      chest: { kind: "scatter" }
    },
    reelCounts: {
      captain: [1, 1, 1, 1, 1],
      ship: [2, 2, 2, 2, 2],
      compass: [3, 3, 3, 3, 3],
      anchor: [4, 4, 4, 4, 4],
      map: [4, 4, 4, 4, 4],
      A: [4, 4, 4, 4, 4],
      K: [4, 4, 4, 4, 4],
      Q: [5, 5, 5, 5, 5],
      J: [5, 5, 5, 5, 5],
      T: [5, 5, 5, 5, 5],
      flag: [1, 1, 1, 1, 1],
      chest: [1, 2, 1, 2, 1]
    },
    features: {
      scatterPays: [2, 10, 40],
      pickBonus: { kind: "chests", picks: [3, 4, 5], values: [2, 5, 10, 20, 50, 100], weights: [30, 28, 20, 12, 7, 3] }
    }
  },
  // Big but rare: a cosmic multiplier (×2–×10) can land on any win; portals open free spins.
  cosmic: {
    id: "cosmic",
    lines: lines(25),
    betLevels: levels(25, [1, 2, 5, 10, 20, 50, 100]),
    top: "alien",
    volatility: "high",
    maxWin: 5e3,
    symbols: {
      alien: reg(325, 1800, 8600),
      planet: reg(200, 700, 2600),
      galaxy: reg(95, 325, 1300),
      crystal: reg(65, 225, 875),
      comet: reg(60, 150, 575),
      A: reg(7, 20, 80),
      K: reg(7, 15, 70),
      Q: reg(5, 15, 60),
      J: reg(4, 15, 55),
      T: reg(4, 15, 55),
      star: { kind: "wild" },
      portal: { kind: "scatter" }
    },
    reelCounts: {
      alien: [1, 1, 1, 1, 1],
      planet: [2, 2, 2, 2, 2],
      galaxy: [3, 3, 3, 3, 3],
      crystal: [3, 3, 3, 3, 3],
      comet: [4, 4, 4, 4, 4],
      A: [4, 4, 4, 4, 4],
      K: [4, 4, 4, 4, 4],
      Q: [4, 4, 4, 4, 4],
      J: [4, 4, 4, 4, 4],
      T: [4, 4, 4, 4, 4],
      star: [0, 1, 1, 1, 0],
      portal: [1, 1, 1, 1, 1]
    },
    features: {
      scatterPays: [2, 10, 50],
      winMultiplier: { chance: 80, values: [2, 3, 5, 10, 25], weights: [45, 30, 15, 7, 3] },
      freeSpins: { count: [7, 10, 15], multiplier: 2, retrigger: true, max: 45 }
    }
  },
  // Built around the jackpot ladder: royal crests anywhere award MINOR / MAJOR / GRAND.
  royal: {
    id: "royal",
    lines: lines(10),
    betLevels: levels(10, [1, 2, 5, 10, 20, 50, 100]),
    top: "crown",
    volatility: "medium-high",
    maxWin: 2e3,
    symbols: {
      crown: reg(175, 850, 3400),
      scepter: reg(95, 400, 1700),
      chalice: reg(70, 275, 1100),
      ring: reg(55, 175, 700),
      shield: reg(35, 150, 525),
      A: reg(20, 55, 225),
      K: reg(20, 45, 175),
      Q: reg(15, 35, 150),
      J: reg(15, 35, 150),
      seal: { kind: "wild", pays: [175, 850, 3400] },
      crest: { kind: "scatter" }
    },
    reelCounts: {
      crown: [2, 2, 2, 2, 2],
      scepter: [3, 3, 3, 3, 3],
      chalice: [3, 3, 3, 3, 3],
      ring: [4, 4, 4, 4, 4],
      shield: [4, 4, 4, 4, 4],
      A: [7, 7, 7, 7, 7],
      K: [7, 7, 7, 7, 7],
      Q: [8, 8, 8, 8, 8],
      J: [8, 8, 8, 8, 8],
      seal: [1, 1, 1, 1, 1],
      crest: [1, 1, 2, 1, 1]
    },
    features: { jackpotLadder: { tiers: [20, 100, 1e3] } }
  }
};
var ALL_BETS = [...new Set(Object.values(MACHINES).flatMap((m) => m.betLevels))].sort((a, b) => a - b);

// src/casino/random.ts
function cryptoUint322() {
  try {
    const c = globalThis.crypto;
    if (!c?.getRandomValues) return null;
    return c.getRandomValues(new Uint32Array(1))[0];
  } catch {
    return null;
  }
}
function secureSeed() {
  return cryptoUint322() ?? Math.floor(Math.random() * 4294967296) >>> 0;
}
function cryptoRng() {
  let last = 0;
  return {
    next() {
      last = secureSeed();
      return last / 4294967296;
    },
    state() {
      return last;
    }
  };
}

// src/casino/slots.ts
var WILD = "star";
var REELS2 = 5;
var REEL = [
  "cactus",
  "hat",
  "bison",
  "horseshoe",
  "revolver",
  "seven",
  "cactus",
  "moneybag",
  "star",
  "horseshoe",
  "wagon",
  "hat",
  "cactus",
  "eagle",
  "revolver",
  "horseshoe",
  "moneybag",
  "gold",
  "hat",
  "cactus",
  "bison",
  "star",
  "horseshoe",
  "wagon",
  "revolver",
  "hat",
  "cactus",
  "moneybag",
  "eagle",
  "horseshoe",
  "bison",
  "star",
  "cactus",
  "hat",
  "wagon",
  "revolver",
  "horseshoe",
  "gold",
  "moneybag"
];
var PAYTABLE = {
  seven: [50, 250, 2500],
  gold: [30, 120, 750],
  eagle: [25, 100, 500],
  bison: [20, 60, 250],
  wagon: [20, 60, 250],
  revolver: [10, 40, 150],
  moneybag: [10, 40, 150],
  hat: [8, 20, 80],
  horseshoe: [4, 12, 50],
  cactus: [4, 12, 50],
  star: [40, 200, 1e3]
};
var LINES = [
  [1, 1, 1, 1, 1],
  [0, 0, 0, 0, 0],
  [2, 2, 2, 2, 2],
  [0, 1, 2, 1, 0],
  [2, 1, 0, 1, 2],
  [0, 0, 1, 2, 2],
  [2, 2, 1, 0, 0],
  [1, 0, 0, 0, 1],
  [1, 2, 2, 2, 1],
  [1, 2, 1, 0, 1]
];
var LINE_OPTIONS = [1, 5, 10];
var BET_PER_LINE = [1, 2, 5, 10, 20];
function evaluateLine(line) {
  const base = line.find((s) => s !== WILD) ?? WILD;
  let count = 0;
  while (count < line.length && (line[count] === base || line[count] === WILD)) count++;
  let wilds = 0;
  while (wilds < line.length && line[wilds] === WILD) wilds++;
  const basePay = count >= 3 ? PAYTABLE[base][count - 3] : 0;
  const wildPay = wilds >= 3 ? PAYTABLE[WILD][wilds - 3] : 0;
  if (basePay === 0 && wildPay === 0) return null;
  return wildPay > basePay ? { symbol: WILD, count: wilds, multiplier: wildPay } : { symbol: base, count, multiplier: basePay };
}
function spinReels(rng) {
  return Array.from({ length: REELS2 }, () => Math.floor(rng.next() * REEL.length));
}
var symbolAt = (stop, offset = 0) => REEL[((stop + offset) % REEL.length + REEL.length) % REEL.length];
function visibleGrid(stops) {
  return stops.map((stop) => [symbolAt(stop, -1), symbolAt(stop), symbolAt(stop, 1)]);
}
function lineSymbols(grid, line) {
  return LINES[line].map((row, reel) => grid[reel][row]);
}
function evaluateSpin2(stops, lineCount, betPerLine) {
  const grid = visibleGrid(stops);
  const wins = [];
  for (let line = 0; line < Math.min(lineCount, LINES.length); line++) {
    const result = evaluateLine(lineSymbols(grid, line));
    if (result) wins.push({ ...result, line, amount: result.multiplier * betPerLine });
  }
  return {
    wins,
    total: wins.reduce((sum, w) => sum + w.amount, 0),
    jackpot: wins.some((w) => w.symbol === "seven" && w.count === 5)
  };
}

// src/casino/roulette.ts
var POCKETS = 37;
var RED_NUMBERS = /* @__PURE__ */ new Set([1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36]);
var PAYOUT = {
  straight: 35,
  red: 1,
  black: 1,
  even: 1,
  odd: 1,
  low: 1,
  high: 1,
  dozen: 2,
  column: 2
};
function betWins(bet, n) {
  if (bet.type === "straight") return bet.value === n;
  if (n === 0) return false;
  switch (bet.type) {
    case "red":
      return RED_NUMBERS.has(n);
    case "black":
      return !RED_NUMBERS.has(n);
    case "even":
      return n % 2 === 0;
    case "odd":
      return n % 2 === 1;
    case "low":
      return n <= 18;
    case "high":
      return n >= 19;
    case "dozen":
      return Math.ceil(n / 12) === bet.value;
    case "column":
      return (n - 1) % 3 + 1 === bet.value;
  }
}
function betPayout(bet, n) {
  return betWins(bet, n) ? bet.amount * (PAYOUT[bet.type] + 1) : 0;
}
function totalPayout(bets, n) {
  return bets.reduce((sum, b) => sum + betPayout(b, n), 0);
}
function spin(rng) {
  return Math.floor(rng.next() * POCKETS);
}

// src/game/engine/rng.ts
function createRng(state) {
  let s = state >>> 0;
  return {
    next() {
      s = s + 1831565813 >>> 0;
      let t = s;
      t = Math.imul(t ^ t >>> 15, t | 1);
      t ^= t + Math.imul(t ^ t >>> 7, t | 61);
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    },
    state() {
      return s;
    }
  };
}

// src/casino/cards.ts
var SUITS = ["S", "H", "D", "C"];
var RANKS = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
function createShoe(decks) {
  const shoe = [];
  for (let d = 0; d < decks; d++) for (const suit of SUITS) for (const rank of RANKS) shoe.push({ id: `${rank}${suit}-${d}`, rank, suit });
  return shoe;
}
function shuffle(items, rng) {
  const out = [...items];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng.next() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

// src/casino/blackjack.ts
var DECKS = 6;
var RESHUFFLE_BELOW = 52;
function cardValue(card) {
  if (card.rank === "A") return 11;
  if (card.rank === "J" || card.rank === "Q" || card.rank === "K") return 10;
  return Number(card.rank);
}
function handTotal(cards) {
  let total = 0;
  let aces = 0;
  for (const c of cards) {
    total += cardValue(c);
    if (c.rank === "A") aces++;
  }
  while (total > 21 && aces > 0) {
    total -= 10;
    aces--;
  }
  return { total, soft: aces > 0 };
}
var isBlackjack = (cards) => cards.length === 2 && handTotal(cards).total === 21;
var isBust = (cards) => handTotal(cards).total > 21;
function createBlackjack(seed) {
  const rng = createRng(seed);
  const shoe = shuffle(createShoe(DECKS), rng);
  return { phase: "BETTING", shoe, rngState: rng.state(), hands: [], active: 0, dealer: [], results: [] };
}
function draw(s, rng) {
  if (s.shoe.length === 0) s.shoe = shuffle(createShoe(DECKS), rng);
  return s.shoe.shift();
}
function clone(s) {
  return { ...s, shoe: [...s.shoe], hands: s.hands.map((h) => ({ ...h, cards: [...h.cards] })), dealer: [...s.dealer], results: [...s.results] };
}
function withRng(state, fn) {
  const s = clone(state);
  const rng = createRng(s.rngState);
  fn(s, rng);
  s.rngState = rng.state();
  return s;
}
function canDeal(s, bet) {
  return (s.phase === "BETTING" || s.phase === "SETTLED") && bet > 0;
}
function deal(state, bet) {
  if (!canDeal(state, bet)) return state;
  return withRng(state, (s, rng) => {
    if (s.shoe.length < RESHUFFLE_BELOW) s.shoe = shuffle(createShoe(DECKS), rng);
    const hand = { cards: [], bet, done: false, doubled: false, fromSplit: false };
    s.dealer = [];
    s.results = [];
    hand.cards.push(draw(s, rng));
    s.dealer.push(draw(s, rng));
    hand.cards.push(draw(s, rng));
    s.dealer.push(draw(s, rng));
    s.hands = [hand];
    s.active = 0;
    s.phase = "PLAYER";
    if (isBlackjack(hand.cards) || isBlackjack(s.dealer)) {
      hand.done = true;
      settle(s);
    }
  });
}
function advance(s, rng) {
  const next = s.hands.findIndex((h) => !h.done);
  if (next >= 0) {
    s.active = next;
    return;
  }
  if (s.hands.some((h) => !isBust(h.cards))) {
    while (handTotal(s.dealer).total < 17) s.dealer.push(draw(s, rng));
  }
  settle(s);
}
function outcomeFor(hand, dealer) {
  const player = handTotal(hand.cards).total;
  const dealerTotal = handTotal(dealer).total;
  const natural = isBlackjack(hand.cards) && !hand.fromSplit;
  const dealerNatural = isBlackjack(dealer);
  if (natural && !dealerNatural) return { outcome: "blackjack", payout: hand.bet + Math.floor(hand.bet * 1.5) };
  if (dealerNatural) return natural ? { outcome: "push", payout: hand.bet } : { outcome: "lose", payout: 0 };
  if (player > 21) return { outcome: "lose", payout: 0 };
  if (dealerTotal > 21 || player > dealerTotal) return { outcome: "win", payout: hand.bet * 2 };
  if (player === dealerTotal) return { outcome: "push", payout: hand.bet };
  return { outcome: "lose", payout: 0 };
}
function settle(s) {
  s.results = s.hands.map((h) => outcomeFor(h, s.dealer));
  s.phase = "SETTLED";
}
function totalPayout2(s) {
  return s.results.reduce((sum, r) => sum + r.payout, 0);
}
var activeHand = (s) => s.phase === "PLAYER" ? s.hands[s.active] : void 0;
function hit(state) {
  if (!activeHand(state)) return state;
  return withRng(state, (s, rng) => {
    const hand = s.hands[s.active];
    hand.cards.push(draw(s, rng));
    if (handTotal(hand.cards).total >= 21) {
      hand.done = true;
      advance(s, rng);
    }
  });
}
function stand(state) {
  if (!activeHand(state)) return state;
  return withRng(state, (s, rng) => {
    s.hands[s.active].done = true;
    advance(s, rng);
  });
}
function canDouble(s) {
  const hand = activeHand(s);
  return !!hand && hand.cards.length === 2 && !hand.doubled;
}
function double(state) {
  if (!canDouble(state)) return state;
  return withRng(state, (s, rng) => {
    const hand = s.hands[s.active];
    hand.bet *= 2;
    hand.doubled = true;
    hand.cards.push(draw(s, rng));
    hand.done = true;
    advance(s, rng);
  });
}
function canSplit(s) {
  const hand = activeHand(s);
  return !!hand && s.hands.length === 1 && hand.cards.length === 2 && cardValue(hand.cards[0]) === cardValue(hand.cards[1]);
}
function split(state) {
  if (!canSplit(state)) return state;
  return withRng(state, (s, rng) => {
    const [a, b] = s.hands[0].cards;
    const bet = s.hands[0].bet;
    const aces = a.rank === "A";
    s.hands = [a, b].map((card) => {
      const hand = { cards: [card, draw(s, rng)], bet, done: aces, doubled: false, fromSplit: true };
      if (handTotal(hand.cards).total === 21) hand.done = true;
      return hand;
    });
    s.active = 0;
    advance(s, rng);
  });
}
function extraStake(s, action) {
  const hand = activeHand(s);
  if (!hand) return 0;
  return action === "double" ? hand.bet : s.hands[0].bet;
}

// src/casino/server/handler.ts
var CasinoStoreError = class extends Error {
  constructor(code) {
    super(code);
    this.code = code;
  }
};
var STATUS = {
  unauthorized: 401,
  account_required: 403,
  insufficient_funds: 402,
  invalid_bet: 400,
  conflict: 409,
  rate_limited: 429,
  bad_request: 400,
  game_disabled: 423,
  server: 500
};
var fail = (code) => ({ status: STATUS[code], body: { code } });
var ok = (body) => ({ status: 200, body });
var MAX_STAKE = 1e5;
var MAX_ROULETTE_BETS = 60;
var BET_TYPES = ["straight", "red", "black", "even", "odd", "low", "high", "dozen", "column"];
function parseBets(x) {
  if (!Array.isArray(x) || x.length === 0 || x.length > MAX_ROULETTE_BETS) return null;
  const out = [];
  let total = 0;
  for (const raw of x) {
    if (!raw || typeof raw !== "object") return null;
    const b = raw;
    const type = b.type;
    if (!BET_TYPES.includes(type)) return null;
    if (typeof b.amount !== "number" || !Number.isInteger(b.amount) || b.amount < 1) return null;
    let value;
    if (type === "straight") {
      if (typeof b.value !== "number" || !Number.isInteger(b.value) || b.value < 0 || b.value > 36) return null;
      value = b.value;
    } else if (type === "dozen" || type === "column") {
      if (typeof b.value !== "number" || !Number.isInteger(b.value) || b.value < 1 || b.value > 3) return null;
      value = b.value;
    } else if (b.value !== void 0) return null;
    total += b.amount;
    out.push(value === void 0 ? { type, amount: b.amount } : { type, value, amount: b.amount });
  }
  return total <= MAX_STAKE ? out : null;
}
var stakeOf = (bets) => bets.reduce((s, b) => s + b.amount, 0);
function bjView(row, balance) {
  const s = row.state;
  const hidden = s.phase === "PLAYER";
  return {
    requestId: row.requestId,
    phase: s.phase,
    hands: s.hands,
    active: s.active,
    dealer: s.dealer.map((c, i) => hidden && i === 1 ? null : c),
    results: s.results,
    stake: row.stake,
    balance
  };
}
var premiumReceipt = (b) => ({
  requestId: b.requestId,
  machine: b.detail.machine,
  bet: b.stake,
  draws: b.detail.draws,
  payout: b.payout,
  balance: b.balance,
  at: b.at
});
async function handleCasinoRequest(req, deps) {
  if (!req.user) return fail("unauthorized");
  const user = req.user;
  if (deps.allow && !deps.allow(user.id)) return fail("rate_limited");
  const rng = deps.rng ?? cryptoRng;
  const seed = deps.seed ?? secureSeed;
  const store2 = deps.store;
  try {
    if (req.method === "GET") {
      if (!user.registered) return fail("account_required");
      const url = new URL(req.url);
      if (url.searchParams.has("balance")) return ok({ balance: (await store2.account(user.id)).balance });
      const requestId2 = url.searchParams.get("requestId");
      if (!isRequestId(requestId2)) return fail("invalid_bet");
      const found = await store2.find(user.id, requestId2.toLowerCase());
      return found && found.game === "premium" ? ok(premiumReceipt(found)) : { status: 404, body: { found: false } };
    }
    if (req.method !== "POST") return fail("bad_request");
    const b = req.body && typeof req.body === "object" ? req.body : {};
    if (b.op === void 0) {
      if (!user.registered) return fail("account_required");
      const { requestId: requestId2, machine, bet } = b;
      if (!isRequestId(requestId2) || !isMachineId(machine) || !isValidBetFor(MACHINES[machine], bet)) return fail("invalid_bet");
      const id = requestId2.toLowerCase();
      const existing = await store2.find(user.id, id);
      if (existing) return existing.game === "premium" && existing.detail.machine === machine && existing.stake === bet ? ok(premiumReceipt(existing)) : fail("conflict");
      if (deps.slotsEnabled && !await deps.slotsEnabled()) return fail("game_disabled");
      const round = playRound(MACHINES[machine], bet, deps.random ?? cryptoUint32);
      const booked = await store2.play({ userId: user.id, requestId: id, game: "premium", stake: bet, payout: round.payout, detail: { machine, draws: round.draws } });
      if (booked.detail.machine !== machine) return fail("conflict");
      return ok(premiumReceipt(booked));
    }
    if (b.op === "account") return ok(await store2.account(user.id));
    if (!user.registered) return fail("account_required");
    const requestId = typeof b.requestId === "string" && isRequestId(b.requestId) ? b.requestId.toLowerCase() : null;
    switch (b.op) {
      case "claim": {
        if (!requestId) return fail("bad_request");
        return ok(await store2.claimBonus(user.id, requestId));
      }
      case "roulette": {
        const bets = parseBets(b.bets);
        if (!requestId || !bets) return fail("invalid_bet");
        const stake = stakeOf(bets);
        const existing = await store2.find(user.id, requestId);
        if (existing) {
          if (existing.game !== "roulette" || existing.stake !== stake) return fail("conflict");
          return ok({ requestId, pocket: existing.detail.pocket, stake, payout: existing.payout, balance: existing.balance });
        }
        const pocket = spin(rng());
        const booked = await store2.play({ userId: user.id, requestId, game: "roulette", stake, payout: totalPayout(bets, pocket), detail: { pocket, bets } });
        return ok({ requestId, pocket: booked.detail.pocket, stake, payout: booked.payout, balance: booked.balance });
      }
      case "slots": {
        const { lines: lines2, betPerLine } = b;
        if (!requestId || !LINE_OPTIONS.includes(lines2) || !BET_PER_LINE.includes(betPerLine)) return fail("invalid_bet");
        const l = lines2;
        const bpl = betPerLine;
        const stake = l * bpl;
        const existing = await store2.find(user.id, requestId);
        const answer = (bk) => ({ requestId, stops: bk.detail.stops, lines: l, betPerLine: bpl, payout: bk.payout, balance: bk.balance });
        if (existing) return existing.game === "slots" && existing.stake === stake && existing.detail.lines === l ? ok(answer(existing)) : fail("conflict");
        if (deps.slotsEnabled && !await deps.slotsEnabled()) return fail("game_disabled");
        const stops = spinReels(rng());
        const outcome = evaluateSpin2(stops, l, bpl);
        return ok(answer(await store2.play({ userId: user.id, requestId, game: "slots", stake, payout: outcome.total, detail: { stops, lines: l, betPerLine: bpl } })));
      }
      case "bj": {
        const row = await store2.bjLoad(user.id);
        const { balance } = await store2.account(user.id);
        return ok({ table: row ? bjView(row, balance) : null, balance });
      }
      case "bj_deal": {
        const bet = b.bet;
        if (!requestId || typeof bet !== "number" || !Number.isInteger(bet) || bet < 1 || bet > MAX_STAKE) return fail("invalid_bet");
        const current = await store2.bjLoad(user.id);
        if (current) {
          if (current.requestId !== requestId) return fail("conflict");
          return ok(bjView(current, (await store2.account(user.id)).balance));
        }
        const state = deal(createBlackjack(seed()), bet);
        let balance = await store2.bjOpen(user.id, requestId, bet, state);
        if (state.phase === "SETTLED") {
          balance = await store2.bjStep(user.id, requestId, 1, 0, state, totalPayout2(state), finalDetail(state));
        }
        return ok(bjView({ requestId, stake: bet, state }, balance));
      }
      case "bj_act": {
        const action = b.action;
        if (!requestId || action !== "hit" && action !== "stand" && action !== "double" && action !== "split") return fail("bad_request");
        const row = await store2.bjLoad(user.id);
        if (!row || row.requestId !== requestId || row.state.phase !== "PLAYER") return fail("conflict");
        const s = row.state;
        if (action === "double" && !canDouble(s)) return fail("bad_request");
        if (action === "split" && !canSplit(s)) return fail("bad_request");
        const extra = action === "double" || action === "split" ? extraStake(s, action) : 0;
        const next = action === "hit" ? hit(s) : action === "stand" ? stand(s) : action === "double" ? double(s) : split(s);
        const settled = next.phase === "SETTLED";
        const balance = await store2.bjStep(user.id, requestId, row.version, extra, next, settled ? totalPayout2(next) : null, settled ? finalDetail(next) : null);
        return ok(bjView({ requestId, stake: row.stake + extra, state: next }, balance));
      }
      default:
        return fail("bad_request");
    }
  } catch (e) {
    if (e instanceof CasinoStoreError) return fail(e.code === "not_registered" ? "account_required" : e.code);
    throw e;
  }
}
function finalDetail(s) {
  return { hands: s.hands, dealer: s.dealer, results: s.results };
}

// supabase/functions/_shared/casinoStore.ts
var toBooking = (r) => ({
  requestId: r.request_id,
  game: r.game,
  stake: Number(r.stake),
  payout: Number(r.payout),
  balance: Number(r.balance),
  detail: r.detail ?? {},
  at: Date.parse(r.created_at)
});
function postgrestCasinoStore(supabaseUrl, serviceKey, fetchImpl = fetch) {
  async function rpc(fn, args) {
    const res = await fetchImpl(`${supabaseUrl}/rest/v1/rpc/${fn}`, {
      method: "POST",
      headers: { "content-type": "application/json", apikey: serviceKey, authorization: `Bearer ${serviceKey}` },
      body: JSON.stringify(args)
    });
    const body = await res.json().catch(() => null);
    if (!res.ok) {
      const code = body?.code;
      if (code === "P0402") throw new CasinoStoreError("insufficient_funds");
      if (code === "P0409") throw new CasinoStoreError("conflict");
      if (code === "P0400") throw new CasinoStoreError("invalid_bet");
      if (code === "P0403") throw new CasinoStoreError("not_registered");
      if (code === "P0423") throw new CasinoStoreError("game_disabled");
      throw new Error(`rpc ${fn} failed: ${res.status}`);
    }
    return body;
  }
  return {
    async account(userId) {
      const rows = await rpc("account_wallet", { p_user: userId });
      const r = rows[0];
      return { balance: Number(r?.balance ?? 0), bonusClaimed: !!r?.bonus_claimed, registered: !!r?.registered };
    },
    async claimBonus(userId, requestId) {
      const rows = await rpc("account_claim_bonus", { p_user: userId, p_request: requestId });
      return { balance: Number(rows[0].balance), granted: rows[0].granted };
    },
    async play(c) {
      const rows = await rpc("account_play", { p_user: c.userId, p_request: c.requestId, p_game: c.game, p_stake: c.stake, p_payout: c.payout, p_detail: c.detail });
      if (!rows?.length) throw new Error("empty booking");
      return { ...toBooking(rows[0]), replayed: !!rows[0].replayed };
    },
    async find(userId, requestId) {
      const rows = await rpc("account_find", { p_user: userId, p_request: requestId });
      return rows?.length ? toBooking(rows[0]) : null;
    },
    async bjLoad(userId) {
      const row = await rpc("bj_load", { p_user: userId });
      return row ? { requestId: row.request_id, stake: Number(row.stake), state: row.state, version: row.version } : null;
    },
    async bjOpen(userId, requestId, stake, state) {
      return Number(await rpc("bj_open", { p_user: userId, p_request: requestId, p_stake: stake, p_state: state }));
    },
    async bjStep(userId, requestId, version, extra, state, payout, detail) {
      return Number(
        await rpc("bj_step", { p_user: userId, p_request: requestId, p_version: version, p_extra: extra, p_state: state, p_payout: payout, p_detail: detail })
      );
    }
  };
}

// supabase/functions/casino/source.ts
var SUPABASE_URL = Deno.env.get("SUPABASE_URL");
var ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY");
var SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
var ALLOWED = /* @__PURE__ */ new Set(["https://siiknotic.github.io", "http://localhost:5173", "http://127.0.0.1:5173", "http://localhost:4173"]);
var store = postgrestCasinoStore(SUPABASE_URL, SERVICE_KEY);
async function slotsEnabled() {
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/game_enabled`, {
      method: "POST",
      headers: { "content-type": "application/json", apikey: SERVICE_KEY, authorization: `Bearer ${SERVICE_KEY}` },
      body: JSON.stringify({ p_game: "slots" })
    });
    return res.ok && await res.json() === true;
  } catch {
    return false;
  }
}
var hits = /* @__PURE__ */ new Map();
function allow(userId) {
  const now = Date.now();
  const recent = (hits.get(userId) ?? []).filter((t) => now - t < 1e3);
  recent.push(now);
  hits.set(userId, recent);
  if (hits.size > 1e4) hits.clear();
  return recent.length <= 8;
}
async function verifiedUser(req) {
  const auth = req.headers.get("authorization") ?? "";
  if (!auth.startsWith("Bearer ")) return null;
  const res = await fetch(`${SUPABASE_URL}/auth/v1/user`, { headers: { apikey: ANON_KEY, authorization: auth } });
  if (!res.ok) return null;
  const u = await res.json().catch(() => null);
  if (typeof u?.id !== "string") return null;
  return { id: u.id, registered: u.is_anonymous !== true && typeof u.email_confirmed_at === "string" };
}
Deno.serve(async (req) => {
  const origin = req.headers.get("origin") ?? "";
  const cors = {
    "access-control-allow-origin": ALLOWED.has(origin) ? origin : "https://siiknotic.github.io",
    "access-control-allow-headers": "authorization, apikey, content-type, x-client-info",
    "access-control-allow-methods": "GET, POST, OPTIONS",
    vary: "origin"
  };
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
  let body = null;
  if (req.method === "POST") {
    const text = await req.text();
    if (text.length > 4096) return Response.json({ code: "bad_request" }, { status: 413, headers: cors });
    try {
      body = JSON.parse(text);
    } catch {
      return Response.json({ code: "bad_request" }, { status: 400, headers: cors });
    }
  }
  try {
    const out = await handleCasinoRequest({ method: req.method, url: req.url, user: await verifiedUser(req), body }, { store, allow, slotsEnabled });
    return Response.json(out.body, { status: out.status, headers: { ...cors, "cache-control": "no-store" } });
  } catch (e) {
    console.error("casino", e instanceof Error ? e.message : e);
    return Response.json({ code: "server" }, { status: 500, headers: cors });
  }
});
