// @ts-nocheck -- generated by npm run functions:build from source.ts; do not edit

// src/casino/premium/engine.ts
var MACHINE_IDS = ["lucky7s", "diamondRoyale", "goldenFortune", "inferno", "tropical", "pirates", "cosmic", "royal"];
var isMachineId = (x) => typeof x === "string" && MACHINE_IDS.includes(x);
var REELS = 5;
function buildStrip(counts) {
  const entries = Object.entries(counts).filter(([, n]) => n > 0);
  const total = entries.reduce((s, [, n]) => s + n, 0);
  const slots = [];
  entries.forEach(([s, n], i) => {
    for (let k = 0; k < n; k++) slots.push({ s, at: (k + 0.5) * total / n + i * 0.013 });
  });
  slots.sort((a, b) => a.at - b.at);
  const strip = slots.map((x) => x.s);
  for (let pass = 0; pass < 3; pass++) {
    for (let i = 0; i < strip.length; i++) {
      const j = (i + 1) % strip.length;
      if (strip[i] !== strip[j]) continue;
      for (let k = 2; k < strip.length; k++) {
        const m = (i + k) % strip.length;
        const prev = strip[(m - 1 + strip.length) % strip.length];
        const next = strip[(m + 1) % strip.length];
        if (strip[m] !== strip[i] && prev !== strip[i] && next !== strip[i] && strip[(i - 1 + strip.length) % strip.length] !== strip[m]) {
          [strip[j], strip[m]] = [strip[m], strip[j]];
          break;
        }
      }
    }
  }
  return strip;
}
var stripCache = /* @__PURE__ */ new WeakMap();
function stripsOf(m) {
  let s = stripCache.get(m);
  if (!s) {
    s = Array.from({ length: REELS }, (_, r) => buildStrip(Object.fromEntries(Object.entries(m.reelCounts).map(([sym, c]) => [sym, c[r]]))));
    stripCache.set(m, s);
  }
  return s;
}
var mod = (x, n) => (x % n + n) % n;
var symbolOn = (strip, stop, offset = 0) => strip[mod(stop + offset, strip.length)];
function gridOf(m, stops) {
  const strips = stripsOf(m);
  return stops.map((stop, r) => [symbolOn(strips[r], stop, -1), symbolOn(strips[r], stop), symbolOn(strips[r], stop, 1)]);
}
function cryptoUint32() {
  const buf = new Uint32Array(1);
  globalThis.crypto.getRandomValues(buf);
  return buf[0];
}
function uniform(n, rand) {
  const limit = Math.floor(4294967296 / n) * n;
  for (; ; ) {
    const x = rand() >>> 0;
    if (x < limit) return x % n;
  }
}
function weighted(w, rand) {
  const total = w.weights.reduce((a, b) => a + b, 0);
  let x = uniform(total, rand);
  for (let i = 0; i < w.values.length; i++) {
    if (x < w.weights[i]) return w.values[i];
    x -= w.weights[i];
  }
  return w.values[w.values.length - 1];
}
function lineResult(m, syms) {
  const wild = Object.keys(m.symbols).find((s) => m.symbols[s].kind === "wild");
  const isWild2 = (s) => s === wild;
  const base = syms.find((s) => !isWild2(s)) ?? wild;
  let count = 0;
  while (count < syms.length && (syms[count] === base || isWild2(syms[count])) && m.symbols[syms[count]].kind !== "scatter") count++;
  let wilds = 0;
  while (wilds < syms.length && isWild2(syms[wilds])) wilds++;
  const basePays = m.symbols[base]?.kind === "regular" && count >= 3 ? m.symbols[base].pays?.[count - 3] ?? 0 : 0;
  const wildPays = wild && wilds >= 3 ? m.symbols[wild].pays?.[wilds - 3] ?? 0 : 0;
  if (!basePays && !wildPays) return null;
  if (wildPays > basePays) return { symbol: wild, count: wilds, pays: wildPays, usesWild: true };
  return { symbol: base, count, pays: basePays, usesWild: syms.slice(0, count).some(isWild2) };
}
function evaluateSpin(m, draw2, bet, freeMult = 1) {
  const lineBet = bet / m.lines.length;
  const grid = gridOf(m, draw2.stops);
  const wild = Object.keys(m.symbols).find((s) => m.symbols[s].kind === "wild");
  const scatter = Object.keys(m.symbols).find((s) => m.symbols[s].kind === "scatter");
  const expanded = (m.features.expandingWild ?? []).filter((r) => wild && grid[r].includes(wild));
  const play = grid.map((col, r) => expanded.includes(r) ? col.map(() => wild) : col);
  const wildMult = draw2.wildMult ?? 1;
  const lines2 = [];
  m.lines.forEach((rows, line) => {
    const res = lineResult(m, rows.map((row, reel) => play[reel][row]));
    if (!res) return;
    const multiplier = res.usesWild ? wildMult : 1;
    lines2.push({ line, symbol: res.symbol, count: res.count, pays: res.pays, multiplier, amount: res.pays * lineBet * multiplier });
  });
  const scatters = scatter ? grid.flat().filter((s) => s === scatter).length : 0;
  const sp = m.features.scatterPays;
  const scatterWin = sp && scatters >= 3 ? sp[Math.min(scatters, 5) - 3] * bet : 0;
  const winMult = draw2.winMult ?? 1;
  const raw = lines2.reduce((s, l) => s + l.amount, 0) + scatterWin;
  const payout = Math.floor(raw * winMult * freeMult);
  return { stops: [...draw2.stops], grid, expanded, lines: lines2, scatters, scatterWin, wildMult, winMult, freeMult, payout };
}
var freeCount = (m, scatters) => {
  const fs = m.features.freeSpins;
  return fs && scatters >= 3 ? fs.count[Math.min(scatters, 5) - 3] : 0;
};
function tierFor(payout, bet, jackpot) {
  if (jackpot) return "jackpot";
  if (payout <= 0) return "none";
  if (payout <= bet) return "tiny";
  if (payout < bet * 10) return "small";
  if (payout < bet * 40) return "big";
  return "mega";
}
function playRound(m, bet, rand = cryptoUint32) {
  if (!isValidBetFor(m, bet)) throw new Error("invalid bet");
  const strips = stripsOf(m);
  const wild = Object.keys(m.symbols).find((s) => m.symbols[s].kind === "wild");
  const drawSpin = () => {
    const stops = strips.map((s) => uniform(s.length, rand));
    const draw2 = { stops };
    const wm = m.features.wildMultiplier;
    if (wm && wild && gridOf(m, stops).some((c) => c.includes(wild))) draw2.wildMult = weighted(wm, rand);
    const xm = m.features.winMultiplier;
    if (xm && evaluateSpin(m, draw2, bet).payout > 0 && uniform(1e3, rand) < xm.chance) draw2.winMult = weighted(xm, rand);
    return draw2;
  };
  const draws = { base: drawSpin(), free: [], picks: [] };
  const base = evaluateSpin(m, draws.base, bet);
  let left = freeCount(m, base.scatters);
  const fs = m.features.freeSpins;
  while (fs && left > 0 && draws.free.length < fs.max) {
    const d = drawSpin();
    draws.free.push(d);
    left--;
    if (fs.retrigger) left += freeCount(m, evaluateSpin(m, d, bet).scatters);
  }
  const pb = m.features.pickBonus;
  if (pb && base.scatters >= 3) for (let i = 0; i < pb.picks[Math.min(base.scatters, 5) - 3]; i++) draws.picks.push(weighted(pb, rand));
  return settleRound(m, bet, draws);
}
function settleRound(m, bet, draws) {
  if (!isValidBetFor(m, bet) || !isValidDraws(m, draws)) throw new Error("invalid round");
  const fs = m.features.freeSpins;
  const base = evaluateSpin(m, draws.base, bet);
  checkMultipliers(m, draws.base, base, bet);
  let expected = freeCount(m, base.scatters);
  const free = [];
  let mult = fs?.multiplier ?? 1;
  for (let i = 0; i < draws.free.length; i++) {
    if (i >= expected) throw new Error("too many free spins");
    const r = evaluateSpin(m, draws.free[i], bet, mult);
    checkMultipliers(m, draws.free[i], r, bet);
    free.push(r);
    if (fs?.retrigger) expected += freeCount(m, r.scatters);
    mult += fs?.step ?? 0;
  }
  if (draws.free.length !== Math.min(expected, fs?.max ?? 0)) throw new Error("missing free spins");
  const pb = m.features.pickBonus;
  const expectedPicks = pb && base.scatters >= 3 ? pb.picks[Math.min(base.scatters, 5) - 3] : 0;
  if (draws.picks.length !== expectedPicks || draws.picks.some((v) => !pb.values.includes(v))) throw new Error("bad picks");
  const pickWin = draws.picks.reduce((s, v) => s + v, 0) * bet;
  const jl = m.features.jackpotLadder;
  const jackpot = jl && base.scatters >= 3 ? ["minor", "major", "grand"][Math.min(base.scatters, 5) - 3] : null;
  const jackpotWin = jackpot && jl ? jl.tiers[["minor", "major", "grand"].indexOf(jackpot)] * bet : 0;
  const topLine = [base, ...free].some((s) => s.lines.some((l) => l.symbol === m.top && l.count === 5));
  const raw = base.payout + free.reduce((s, f) => s + f.payout, 0) + pickWin + jackpotWin;
  const cap = m.maxWin * bet;
  const payout = Math.min(raw, cap);
  const isJackpot = topLine || jackpot === "major" || jackpot === "grand";
  return {
    draws,
    base,
    free,
    freeAwarded: draws.free.length,
    picks: [...draws.picks],
    pickWin,
    jackpot,
    jackpotWin,
    topLine,
    raw,
    payout,
    capped: raw > cap,
    tier: tierFor(payout, bet, isJackpot)
  };
}
function checkMultipliers(m, d, r, bet) {
  const wild = Object.keys(m.symbols).find((s) => m.symbols[s].kind === "wild");
  const wm = m.features.wildMultiplier;
  const wildVisible = !!wild && r.grid.some((c) => c.includes(wild));
  if (d.wildMult !== void 0 && (!wm || !wildVisible || !wm.values.includes(d.wildMult))) throw new Error("bad wild multiplier");
  if (wm && wildVisible && d.wildMult === void 0) throw new Error("missing wild multiplier");
  const xm = m.features.winMultiplier;
  if (d.winMult !== void 0) {
    const plain = evaluateSpin(m, { stops: d.stops, wildMult: d.wildMult }, bet);
    if (!xm || plain.payout <= 0 || !xm.values.includes(d.winMult)) throw new Error("bad win multiplier");
  }
}
var isValidBetFor = (m, bet) => typeof bet === "number" && m.betLevels.includes(bet);
function isValidStopsFor(m, stops) {
  const strips = stripsOf(m);
  return Array.isArray(stops) && stops.length === REELS && stops.every((s, r) => Number.isInteger(s) && s >= 0 && s < strips[r].length);
}
function isValidSpinDraw(m, d) {
  if (!d || typeof d !== "object") return false;
  const x = d;
  const num = (v) => v === void 0 || typeof v === "number" && Number.isFinite(v);
  const keys = Object.keys(x).every((k) => k === "stops" || k === "wildMult" || k === "winMult");
  return keys && isValidStopsFor(m, x.stops) && num(x.wildMult) && num(x.winMult);
}
function isValidDraws(m, d) {
  if (!d || typeof d !== "object") return false;
  const x = d;
  return isValidSpinDraw(m, x.base) && Array.isArray(x.free) && x.free.length <= 500 && x.free.every((f) => isValidSpinDraw(m, f)) && Array.isArray(x.picks) && x.picks.length <= 10 && x.picks.every((p) => typeof p === "number" && Number.isFinite(p));
}
var REQUEST_ID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var isRequestId = (x) => typeof x === "string" && REQUEST_ID_RE.test(x);

// src/casino/premium/machines.ts
var ALL_LINES = [
  [1, 1, 1, 1, 1],
  [0, 0, 0, 0, 0],
  [2, 2, 2, 2, 2],
  [0, 1, 2, 1, 0],
  [2, 1, 0, 1, 2],
  [0, 0, 1, 2, 2],
  [2, 2, 1, 0, 0],
  [1, 0, 0, 0, 1],
  [1, 2, 2, 2, 1],
  [1, 2, 1, 0, 1],
  [1, 0, 1, 2, 1],
  [0, 1, 1, 1, 0],
  [2, 1, 1, 1, 2],
  [0, 1, 0, 1, 0],
  [2, 1, 2, 1, 2],
  [1, 1, 0, 1, 1],
  [1, 1, 2, 1, 1],
  [0, 0, 2, 0, 0],
  [2, 2, 0, 2, 2],
  [0, 2, 2, 2, 0],
  [2, 0, 0, 0, 2],
  [1, 0, 2, 0, 1],
  [1, 2, 0, 2, 1],
  [0, 2, 0, 2, 0],
  [2, 0, 2, 0, 2]
];
var lines = (n) => ALL_LINES.slice(0, n);
var levels = (lineCount, coins) => coins.map((c) => c * lineCount);
var reg = (a, b, c) => ({ kind: "regular", pays: [a, b, c] });
var MACHINES = {
  // Classic Vegas stepper: 22-stop reels, a Wild 7, frequent small pays, bells pay anywhere.
  lucky7s: {
    id: "lucky7s",
    lines: lines(5),
    betLevels: levels(5, [2, 4, 10, 20, 40, 100, 200]),
    top: "seven",
    volatility: "low",
    maxWin: 1e3,
    symbols: {
      seven: reg(75, 375, 2e3),
      bar3: reg(40, 150, 600),
      bar2: reg(25, 75, 275),
      bar: reg(15, 45, 150),
      coin: reg(8, 25, 95),
      cherry: reg(6, 15, 45),
      lemon: reg(4, 10, 40),
      wild7: { kind: "wild", pays: [75, 375, 2e3] },
      bell: { kind: "scatter" }
    },
    // 22 stops per reel, like a mechanical reel.
    reelCounts: {
      seven: [1, 1, 1, 1, 1],
      bar3: [1, 1, 1, 1, 1],
      bar2: [2, 2, 2, 2, 2],
      bar: [2, 2, 2, 2, 2],
      coin: [3, 3, 3, 3, 3],
      cherry: [7, 7, 7, 7, 7],
      lemon: [6, 6, 6, 6, 6],
      wild7: [1, 1, 1, 1, 1],
      bell: [1, 1, 1, 1, 1]
    },
    features: { scatterPays: [2, 10, 50] }
  },
  // Fewer small wins; the crystal wild appears only on reels 2–4 and fills its reel.
  diamondRoyale: {
    id: "diamondRoyale",
    lines: lines(10),
    betLevels: levels(10, [1, 2, 5, 10, 20, 50, 100]),
    top: "diamond",
    volatility: "medium",
    maxWin: 2500,
    symbols: {
      diamond: reg(80, 400, 2200),
      crown: reg(45, 175, 900),
      ruby: reg(30, 125, 450),
      sapphire: reg(25, 90, 300),
      emerald: reg(20, 60, 225),
      ring: reg(15, 45, 150),
      A: reg(9, 25, 90),
      K: reg(9, 20, 80),
      Q: reg(7, 15, 60),
      J: reg(7, 15, 60),
      crystal: { kind: "wild" }
    },
    reelCounts: {
      diamond: [2, 2, 2, 2, 2],
      crown: [3, 3, 3, 3, 3],
      ruby: [3, 3, 3, 3, 3],
      sapphire: [4, 4, 4, 4, 4],
      emerald: [4, 4, 4, 4, 4],
      ring: [5, 5, 5, 5, 5],
      A: [8, 8, 8, 8, 8],
      K: [8, 8, 8, 8, 8],
      Q: [8, 8, 8, 8, 8],
      J: [8, 8, 8, 8, 8],
      crystal: [0, 2, 2, 2, 0]
    },
    features: { expandingWild: [1, 2, 3] }
  },
  // Coins pay anywhere and open the Coin Vault pick bonus.
  goldenFortune: {
    id: "goldenFortune",
    lines: lines(20),
    betLevels: levels(20, [1, 2, 5, 10, 20, 50, 100]),
    top: "idol",
    volatility: "medium-high",
    maxWin: 3e3,
    symbols: {
      idol: reg(225, 1400, 7100),
      ingot: reg(150, 550, 2300),
      scarab: reg(95, 375, 1400),
      sundisk: reg(70, 225, 950),
      hourglass: reg(45, 175, 725),
      A: reg(25, 70, 350),
      K: reg(25, 55, 275),
      Q: reg(20, 45, 225),
      J: reg(15, 35, 175),
      T: reg(15, 35, 175),
      mask: { kind: "wild", pays: [225, 1400, 7100] },
      coin: { kind: "scatter" }
    },
    reelCounts: {
      idol: [2, 2, 2, 2, 2],
      ingot: [3, 3, 3, 3, 3],
      scarab: [3, 3, 3, 3, 3],
      sundisk: [4, 4, 4, 4, 4],
      hourglass: [4, 4, 4, 4, 4],
      A: [5, 5, 5, 5, 5],
      K: [5, 5, 5, 5, 5],
      Q: [6, 6, 6, 6, 6],
      J: [6, 6, 6, 6, 6],
      T: [6, 6, 6, 6, 6],
      mask: [1, 1, 1, 1, 1],
      coin: [1, 1, 2, 1, 1]
    },
    features: {
      scatterPays: [2, 5, 20],
      pickBonus: { kind: "coins", picks: [4, 5, 6], values: [1, 2, 3, 5, 10, 25], weights: [30, 25, 20, 14, 8, 3] }
    }
  },
  // Rare, heavy hits: fire wilds multiply the line, free spins raise the multiplier every spin.
  inferno: {
    id: "inferno",
    lines: lines(20),
    betLevels: levels(20, [1, 2, 5, 10, 20, 50, 100]),
    top: "dragon",
    volatility: "high",
    maxWin: 5e3,
    symbols: {
      dragon: reg(175, 925, 3800),
      phoenix: reg(75, 375, 1500),
      skull: reg(35, 175, 575),
      lava: reg(25, 70, 225),
      A: reg(3, 9, 45),
      K: reg(3, 9, 35),
      Q: reg(2, 7, 35),
      J: reg(2, 7, 35),
      T: reg(2, 7, 25),
      fire: { kind: "wild" },
      volcano: { kind: "scatter" }
    },
    reelCounts: {
      dragon: [1, 1, 1, 1, 1],
      phoenix: [2, 2, 2, 2, 2],
      skull: [3, 3, 3, 3, 3],
      lava: [4, 4, 4, 4, 4],
      A: [4, 4, 4, 4, 4],
      K: [4, 4, 4, 4, 4],
      Q: [4, 4, 4, 4, 4],
      J: [4, 4, 4, 4, 4],
      T: [4, 4, 4, 4, 4],
      fire: [0, 1, 1, 1, 0],
      volcano: [1, 1, 1, 1, 1]
    },
    features: {
      scatterPays: [2, 10, 50],
      wildMultiplier: { values: [2, 3, 5, 10], weights: [50, 30, 15, 5] },
      freeSpins: { count: [8, 12, 16], multiplier: 1, step: 1, retrigger: false, max: 16 }
    }
  },
  // Plenty of small wins; the island opens free spins where every win pays double.
  tropical: {
    id: "tropical",
    lines: lines(15),
    betLevels: levels(15, [1, 2, 5, 10, 20, 50, 100]),
    top: "parrot",
    volatility: "medium",
    maxWin: 1500,
    symbols: {
      parrot: reg(175, 725, 2900),
      sailboat: reg(125, 400, 1500),
      fish: reg(75, 250, 950),
      shell: reg(60, 175, 725),
      hibiscus: reg(50, 125, 475),
      banana: reg(25, 65, 200),
      citrus: reg(20, 50, 150),
      grape: reg(15, 40, 150),
      cherry: reg(15, 30, 100),
      palm: { kind: "wild", pays: [175, 725, 2900] },
      island: { kind: "scatter" }
    },
    reelCounts: {
      parrot: [2, 2, 2, 2, 2],
      sailboat: [3, 3, 3, 3, 3],
      fish: [4, 4, 4, 4, 4],
      shell: [4, 4, 4, 4, 4],
      hibiscus: [5, 5, 5, 5, 5],
      banana: [8, 8, 8, 8, 8],
      citrus: [8, 8, 8, 8, 8],
      grape: [9, 9, 9, 9, 9],
      cherry: [9, 9, 9, 9, 9],
      palm: [1, 1, 1, 1, 1],
      island: [2, 1, 2, 1, 2]
    },
    features: {
      scatterPays: [1, 5, 20],
      freeSpins: { count: [10, 15, 20], multiplier: 2, retrigger: true, max: 50 }
    }
  },
  // Treasure chests open the chest bonus; big symbol pays.
  pirates: {
    id: "pirates",
    lines: lines(20),
    betLevels: levels(20, [1, 2, 5, 10, 20, 50, 100]),
    top: "captain",
    volatility: "medium-high",
    maxWin: 3500,
    symbols: {
      captain: reg(175, 800, 5300),
      ship: reg(100, 400, 1600),
      compass: reg(65, 225, 800),
      anchor: reg(35, 125, 525),
      map: reg(25, 100, 400),
      A: reg(10, 35, 175),
      K: reg(10, 30, 150),
      Q: reg(10, 25, 125),
      J: reg(9, 20, 100),
      T: reg(9, 20, 100),
      flag: { kind: "wild", pays: [175, 800, 5300] },
      chest: { kind: "scatter" }
    },
    reelCounts: {
      captain: [1, 1, 1, 1, 1],
      ship: [2, 2, 2, 2, 2],
      compass: [3, 3, 3, 3, 3],
      anchor: [4, 4, 4, 4, 4],
      map: [4, 4, 4, 4, 4],
      A: [4, 4, 4, 4, 4],
      K: [4, 4, 4, 4, 4],
      Q: [5, 5, 5, 5, 5],
      J: [5, 5, 5, 5, 5],
      T: [5, 5, 5, 5, 5],
      flag: [1, 1, 1, 1, 1],
      chest: [1, 2, 1, 2, 1]
    },
    features: {
      scatterPays: [2, 10, 40],
      pickBonus: { kind: "chests", picks: [3, 4, 5], values: [2, 5, 10, 20, 50, 100], weights: [30, 28, 20, 12, 7, 3] }
    }
  },
  // Big but rare: a cosmic multiplier (×2–×10) can land on any win; portals open free spins.
  cosmic: {
    id: "cosmic",
    lines: lines(25),
    betLevels: levels(25, [1, 2, 5, 10, 20, 50, 100]),
    top: "alien",
    volatility: "high",
    maxWin: 5e3,
    symbols: {
      alien: reg(325, 1800, 8600),
      planet: reg(200, 700, 2600),
      galaxy: reg(95, 325, 1300),
      crystal: reg(65, 225, 875),
      comet: reg(60, 150, 575),
      A: reg(7, 20, 80),
      K: reg(7, 15, 70),
      Q: reg(5, 15, 60),
      J: reg(4, 15, 55),
      T: reg(4, 15, 55),
      star: { kind: "wild" },
      portal: { kind: "scatter" }
    },
    reelCounts: {
      alien: [1, 1, 1, 1, 1],
      planet: [2, 2, 2, 2, 2],
      galaxy: [3, 3, 3, 3, 3],
      crystal: [3, 3, 3, 3, 3],
      comet: [4, 4, 4, 4, 4],
      A: [4, 4, 4, 4, 4],
      K: [4, 4, 4, 4, 4],
      Q: [4, 4, 4, 4, 4],
      J: [4, 4, 4, 4, 4],
      T: [4, 4, 4, 4, 4],
      star: [0, 1, 1, 1, 0],
      portal: [1, 1, 1, 1, 1]
    },
    features: {
      scatterPays: [2, 10, 50],
      winMultiplier: { chance: 80, values: [2, 3, 5, 10, 25], weights: [45, 30, 15, 7, 3] },
      freeSpins: { count: [7, 10, 15], multiplier: 2, retrigger: true, max: 45 }
    }
  },
  // Built around the jackpot ladder: royal crests anywhere award MINOR / MAJOR / GRAND.
  royal: {
    id: "royal",
    lines: lines(10),
    betLevels: levels(10, [1, 2, 5, 10, 20, 50, 100]),
    top: "crown",
    volatility: "medium-high",
    maxWin: 2e3,
    symbols: {
      crown: reg(175, 850, 3400),
      scepter: reg(95, 400, 1700),
      chalice: reg(70, 275, 1100),
      ring: reg(55, 175, 700),
      shield: reg(35, 150, 525),
      A: reg(20, 55, 225),
      K: reg(20, 45, 175),
      Q: reg(15, 35, 150),
      J: reg(15, 35, 150),
      seal: { kind: "wild", pays: [175, 850, 3400] },
      crest: { kind: "scatter" }
    },
    reelCounts: {
      crown: [2, 2, 2, 2, 2],
      scepter: [3, 3, 3, 3, 3],
      chalice: [3, 3, 3, 3, 3],
      ring: [4, 4, 4, 4, 4],
      shield: [4, 4, 4, 4, 4],
      A: [7, 7, 7, 7, 7],
      K: [7, 7, 7, 7, 7],
      Q: [8, 8, 8, 8, 8],
      J: [8, 8, 8, 8, 8],
      seal: [1, 1, 1, 1, 1],
      crest: [1, 1, 2, 1, 1]
    },
    features: { jackpotLadder: { tiers: [20, 100, 1e3] } }
  }
};
var ALL_BETS = [...new Set(Object.values(MACHINES).flatMap((m) => m.betLevels))].sort((a, b) => a - b);

// src/casino/random.ts
function cryptoUint322() {
  try {
    const c = globalThis.crypto;
    if (!c?.getRandomValues) return null;
    return c.getRandomValues(new Uint32Array(1))[0];
  } catch {
    return null;
  }
}
function secureSeed() {
  return cryptoUint322() ?? Math.floor(Math.random() * 4294967296) >>> 0;
}
function cryptoRng() {
  let last = 0;
  return {
    next() {
      last = secureSeed();
      return last / 4294967296;
    },
    state() {
      return last;
    }
  };
}

// src/casino/slots.ts
var WILD = "star";
var REELS2 = 5;
var REEL = [
  "cactus",
  "hat",
  "bison",
  "horseshoe",
  "revolver",
  "seven",
  "cactus",
  "moneybag",
  "star",
  "horseshoe",
  "wagon",
  "hat",
  "cactus",
  "eagle",
  "revolver",
  "horseshoe",
  "moneybag",
  "gold",
  "hat",
  "cactus",
  "bison",
  "star",
  "horseshoe",
  "wagon",
  "revolver",
  "hat",
  "cactus",
  "moneybag",
  "eagle",
  "horseshoe",
  "bison",
  "star",
  "cactus",
  "hat",
  "wagon",
  "revolver",
  "horseshoe",
  "gold",
  "moneybag"
];
var PAYTABLE = {
  seven: [50, 250, 2500],
  gold: [30, 120, 750],
  eagle: [25, 100, 500],
  bison: [20, 60, 250],
  wagon: [20, 60, 250],
  revolver: [10, 40, 150],
  moneybag: [10, 40, 150],
  hat: [8, 20, 80],
  horseshoe: [4, 12, 50],
  cactus: [4, 12, 50],
  star: [40, 200, 1e3]
};
var LINES = [
  [1, 1, 1, 1, 1],
  [0, 0, 0, 0, 0],
  [2, 2, 2, 2, 2],
  [0, 1, 2, 1, 0],
  [2, 1, 0, 1, 2],
  [0, 0, 1, 2, 2],
  [2, 2, 1, 0, 0],
  [1, 0, 0, 0, 1],
  [1, 2, 2, 2, 1],
  [1, 2, 1, 0, 1]
];
var LINE_OPTIONS = [1, 5, 10];
var BET_PER_LINE = [1, 2, 5, 10, 20];
function evaluateLine(line) {
  const base = line.find((s) => s !== WILD) ?? WILD;
  let count = 0;
  while (count < line.length && (line[count] === base || line[count] === WILD)) count++;
  let wilds = 0;
  while (wilds < line.length && line[wilds] === WILD) wilds++;
  const basePay = count >= 3 ? PAYTABLE[base][count - 3] : 0;
  const wildPay = wilds >= 3 ? PAYTABLE[WILD][wilds - 3] : 0;
  if (basePay === 0 && wildPay === 0) return null;
  return wildPay > basePay ? { symbol: WILD, count: wilds, multiplier: wildPay } : { symbol: base, count, multiplier: basePay };
}
function spinReels(rng) {
  return Array.from({ length: REELS2 }, () => Math.floor(rng.next() * REEL.length));
}
var symbolAt = (stop, offset = 0) => REEL[((stop + offset) % REEL.length + REEL.length) % REEL.length];
function visibleGrid(stops) {
  return stops.map((stop) => [symbolAt(stop, -1), symbolAt(stop), symbolAt(stop, 1)]);
}
function lineSymbols(grid, line) {
  return LINES[line].map((row, reel) => grid[reel][row]);
}
function evaluateSpin2(stops, lineCount, betPerLine) {
  const grid = visibleGrid(stops);
  const wins = [];
  for (let line = 0; line < Math.min(lineCount, LINES.length); line++) {
    const result = evaluateLine(lineSymbols(grid, line));
    if (result) wins.push({ ...result, line, amount: result.multiplier * betPerLine });
  }
  return {
    wins,
    total: wins.reduce((sum, w) => sum + w.amount, 0),
    jackpot: wins.some((w) => w.symbol === "seven" && w.count === 5)
  };
}

// src/casino/roulette.ts
var POCKETS = 37;
var RED_NUMBERS = /* @__PURE__ */ new Set([1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36]);
var PAYOUT = {
  straight: 35,
  red: 1,
  black: 1,
  even: 1,
  odd: 1,
  low: 1,
  high: 1,
  dozen: 2,
  column: 2
};
function betWins(bet, n) {
  if (bet.type === "straight") return bet.value === n;
  if (n === 0) return false;
  switch (bet.type) {
    case "red":
      return RED_NUMBERS.has(n);
    case "black":
      return !RED_NUMBERS.has(n);
    case "even":
      return n % 2 === 0;
    case "odd":
      return n % 2 === 1;
    case "low":
      return n <= 18;
    case "high":
      return n >= 19;
    case "dozen":
      return Math.ceil(n / 12) === bet.value;
    case "column":
      return (n - 1) % 3 + 1 === bet.value;
  }
}
function betPayout(bet, n) {
  return betWins(bet, n) ? bet.amount * (PAYOUT[bet.type] + 1) : 0;
}
function totalPayout(bets, n) {
  return bets.reduce((sum, b) => sum + betPayout(b, n), 0);
}
function spin(rng) {
  return Math.floor(rng.next() * POCKETS);
}

// src/game/engine/rng.ts
function createRng(state) {
  let s = state >>> 0;
  return {
    next() {
      s = s + 1831565813 >>> 0;
      let t = s;
      t = Math.imul(t ^ t >>> 15, t | 1);
      t ^= t + Math.imul(t ^ t >>> 7, t | 61);
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    },
    state() {
      return s;
    }
  };
}

// src/casino/cards.ts
var SUITS = ["S", "H", "D", "C"];
var RANKS = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
function createShoe(decks) {
  const shoe = [];
  for (let d = 0; d < decks; d++) for (const suit of SUITS) for (const rank of RANKS) shoe.push({ id: `${rank}${suit}-${d}`, rank, suit });
  return shoe;
}
function shuffle(items, rng) {
  const out = [...items];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng.next() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

// src/casino/blackjack.ts
var DECKS = 6;
var RESHUFFLE_BELOW = 52;
function cardValue(card) {
  if (card.rank === "A") return 11;
  if (card.rank === "J" || card.rank === "Q" || card.rank === "K") return 10;
  return Number(card.rank);
}
function handTotal(cards) {
  let total = 0;
  let aces = 0;
  for (const c of cards) {
    total += cardValue(c);
    if (c.rank === "A") aces++;
  }
  while (total > 21 && aces > 0) {
    total -= 10;
    aces--;
  }
  return { total, soft: aces > 0 };
}
var isBlackjack = (cards) => cards.length === 2 && handTotal(cards).total === 21;
var isBust = (cards) => handTotal(cards).total > 21;
function createBlackjack(seed) {
  const rng = createRng(seed);
  const shoe = shuffle(createShoe(DECKS), rng);
  return { phase: "BETTING", shoe, rngState: rng.state(), hands: [], active: 0, dealer: [], results: [] };
}
function draw(s, rng) {
  if (s.shoe.length === 0) s.shoe = shuffle(createShoe(DECKS), rng);
  return s.shoe.shift();
}
function clone(s) {
  return { ...s, shoe: [...s.shoe], hands: s.hands.map((h) => ({ ...h, cards: [...h.cards] })), dealer: [...s.dealer], results: [...s.results] };
}
function withRng(state, fn) {
  const s = clone(state);
  const rng = createRng(s.rngState);
  fn(s, rng);
  s.rngState = rng.state();
  return s;
}
function canDeal(s, bet) {
  return (s.phase === "BETTING" || s.phase === "SETTLED") && bet > 0;
}
function deal(state, bet) {
  if (!canDeal(state, bet)) return state;
  return withRng(state, (s, rng) => {
    if (s.shoe.length < RESHUFFLE_BELOW) s.shoe = shuffle(createShoe(DECKS), rng);
    const hand = { cards: [], bet, done: false, doubled: false, fromSplit: false };
    s.dealer = [];
    s.results = [];
    hand.cards.push(draw(s, rng));
    s.dealer.push(draw(s, rng));
    hand.cards.push(draw(s, rng));
    s.dealer.push(draw(s, rng));
    s.hands = [hand];
    s.active = 0;
    s.phase = "PLAYER";
    if (isBlackjack(hand.cards) || isBlackjack(s.dealer)) {
      hand.done = true;
      settle(s);
    }
  });
}
function advance(s, rng) {
  const next = s.hands.findIndex((h) => !h.done);
  if (next >= 0) {
    s.active = next;
    return;
  }
  if (s.hands.some((h) => !isBust(h.cards))) {
    while (handTotal(s.dealer).total < 17) s.dealer.push(draw(s, rng));
  }
  settle(s);
}
function outcomeFor(hand, dealer) {
  const player = handTotal(hand.cards).total;
  const dealerTotal = handTotal(dealer).total;
  const natural = isBlackjack(hand.cards) && !hand.fromSplit;
  const dealerNatural = isBlackjack(dealer);
  if (natural && !dealerNatural) return { outcome: "blackjack", payout: hand.bet + Math.floor(hand.bet * 1.5) };
  if (dealerNatural) return natural ? { outcome: "push", payout: hand.bet } : { outcome: "lose", payout: 0 };
  if (player > 21) return { outcome: "lose", payout: 0 };
  if (dealerTotal > 21 || player > dealerTotal) return { outcome: "win", payout: hand.bet * 2 };
  if (player === dealerTotal) return { outcome: "push", payout: hand.bet };
  return { outcome: "lose", payout: 0 };
}
function settle(s) {
  s.results = s.hands.map((h) => outcomeFor(h, s.dealer));
  s.phase = "SETTLED";
}
function totalPayout2(s) {
  return s.results.reduce((sum, r) => sum + r.payout, 0);
}
var activeHand = (s) => s.phase === "PLAYER" ? s.hands[s.active] : void 0;
function hit(state) {
  if (!activeHand(state)) return state;
  return withRng(state, (s, rng) => {
    const hand = s.hands[s.active];
    hand.cards.push(draw(s, rng));
    if (handTotal(hand.cards).total >= 21) {
      hand.done = true;
      advance(s, rng);
    }
  });
}
function stand(state) {
  if (!activeHand(state)) return state;
  return withRng(state, (s, rng) => {
    s.hands[s.active].done = true;
    advance(s, rng);
  });
}
function canDouble(s) {
  const hand = activeHand(s);
  return !!hand && hand.cards.length === 2 && !hand.doubled;
}
function double(state) {
  if (!canDouble(state)) return state;
  return withRng(state, (s, rng) => {
    const hand = s.hands[s.active];
    hand.bet *= 2;
    hand.doubled = true;
    hand.cards.push(draw(s, rng));
    hand.done = true;
    advance(s, rng);
  });
}
function canSplit(s) {
  const hand = activeHand(s);
  return !!hand && s.hands.length === 1 && hand.cards.length === 2 && cardValue(hand.cards[0]) === cardValue(hand.cards[1]);
}
function split(state) {
  if (!canSplit(state)) return state;
  return withRng(state, (s, rng) => {
    const [a, b] = s.hands[0].cards;
    const bet = s.hands[0].bet;
    const aces = a.rank === "A";
    s.hands = [a, b].map((card) => {
      const hand = { cards: [card, draw(s, rng)], bet, done: aces, doubled: false, fromSplit: true };
      if (handTotal(hand.cards).total === 21) hand.done = true;
      return hand;
    });
    s.active = 0;
    advance(s, rng);
  });
}
function extraStake(s, action) {
  const hand = activeHand(s);
  if (!hand) return 0;
  return action === "double" ? hand.bet : s.hands[0].bet;
}

// src/games/online/protocol.ts
var STAKES = [0, 100, 500, 1e3, 5e3];

// src/games/airhockey/table.ts
var W = 1e3;
var H = 1700;
var MID = H / 2;
var PUCK_R = 36;
var MALLET_R = 60;
var GOAL_W = 330;
var GOAL_X0 = (W - GOAL_W) / 2;
var GOAL_X1 = (W + GOAL_W) / 2;
var PLAYER_HOME = { x: W / 2, y: H - 170 };
var AI_HOME = { x: W / 2, y: 170 };
var clamp = (v, lo, hi) => v < lo ? lo : v > hi ? hi : v;

// src/games/airhockey/ai.ts
var AI_LEVEL_IDS = ["easy", "normal", "hard"];
var AI_LEVELS = {
  easy: { react: 14, speed: 1250, noise: 130, miss: 0.3, guard: 200, foresight: 0.45 },
  normal: { react: 7, speed: 1900, noise: 65, miss: 0.12, guard: 175, foresight: 0.8 },
  hard: { react: 3, speed: 2650, noise: 24, miss: 0.04, guard: 150, foresight: 1 }
};
var REACH = PUCK_R + MALLET_R;
var span = W - 2 * PUCK_R;
function foldX(x, vx, t) {
  let u = x - PUCK_R + vx * t;
  const period = 2 * span;
  u -= Math.floor(u / period) * period;
  if (u > span) u = period - u;
  return u + PUCK_R;
}
function aiThink(s, rng) {
  const mem = s.mem;
  if (mem.wait > 0) return { ...mem, wait: mem.wait - 1 };
  const lv = AI_LEVELS[s.level];
  let aim = mem.aim;
  const next = (tx2, ty) => ({ tx: clamp(tx2, MALLET_R, W - MALLET_R), ty: clamp(ty, MALLET_R, MID - MALLET_R), wait: lv.react - 1, aim });
  const jitter = () => (rng.next() - 0.5) * 2 * lv.noise;
  if (s.phase !== "play") {
    aim = null;
    return next(AI_HOME.x, AI_HOME.y);
  }
  const p = s.puck;
  const m = s.ai;
  if (p.y < MID - 4) {
    if (p.y < m.y - 12) {
      const side = p.x < W / 2 ? 1 : -1;
      return next(p.x + side * (REACH + 30), p.y - 40);
    }
    if (aim === null) {
      const corner = rng.next() < 0.5 ? GOAL_X0 + 45 : GOAL_X1 - 45;
      const kind = rng.next();
      if (kind < 0.25 && p.x > 280) aim = 2 * PUCK_R - corner;
      else if (kind < 0.5 && p.x < W - 280) aim = 2 * (W - PUCK_R) - corner;
      else aim = corner;
    }
    const aimX = aim + jitter();
    const aimY = H + 60;
    let dx = aimX - p.x;
    let dy = aimY - p.y;
    const d = Math.sqrt(dx * dx + dy * dy);
    dx /= d;
    dy /= d;
    const bx = m.x - p.x;
    const by = m.y - p.y;
    const along = bx * dx + by * dy;
    const across = bx * dy - by * dx;
    if (along < -REACH * 0.6 && across * across < 60 * 60) {
      let tx2 = p.x + dx * 150;
      const ty = p.y + dy * 150;
      if (rng.next() < lv.miss) tx2 += (rng.next() - 0.5) * 520;
      return next(tx2, ty);
    }
    return next(p.x - dx * (REACH + 28) + jitter() * 0.3, p.y - dy * (REACH + 28));
  }
  aim = null;
  let px = p.x;
  if (p.vy < -60) {
    const t = (p.y - lv.guard) / -p.vy * lv.foresight;
    px = foldX(p.x, p.vx, t);
  }
  const centre = W / 2;
  const tx = clamp(centre + (px - centre) * 0.7 + jitter() * 0.5, GOAL_X0 - 50, GOAL_X1 + 50);
  return next(tx, lv.guard);
}

// src/games/airhockey/rules.ts
var AH_STAKES = STAKES.filter((s) => s > 0);
var isAiLevel = (x) => AI_LEVEL_IDS.includes(x);

// src/games/airhockey/engine.ts
var TICK_HZ = 60;
var SUB = 4;
var DT = 1 / (TICK_HZ * SUB);
var WIN_SCORE = 7;
var MAX_TICKS = TICK_HZ * 60 * 8;
var PUCK_MAX = 2600;
var PLAYER_SPEED = 3400;
var WALL_E = 0.88;
var MALLET_E = 0.9;
var FRICTION = 0.99935;
var STALL_TICKS = TICK_HZ * 3;
var HALF_TICKS = TICK_HZ * 9;
var COUNTDOWN_TICKS = TICK_HZ * 3;
var GOAL_TICKS = Math.round(TICK_HZ * 1.4);
var SERVE_TICKS = Math.round(TICK_HZ * 0.8);
function clampInput(x, y) {
  return { x: Math.round(clamp(x, MALLET_R, W - MALLET_R)), y: Math.round(clamp(y, MID + MALLET_R, H - MALLET_R)) };
}
function servePuck(s, to) {
  const r = createRng(s.rng);
  const off = (r.next() - 0.5) * 240;
  s.rng = r.state();
  s.puck = { x: W / 2 + off, y: to === "player" ? H * 0.7 : H * 0.3, vx: 0, vy: 0 };
  s.stall = 0;
  s.inHalf = 0;
}
function createMatch(seed, level) {
  const s = {
    level,
    tick: 0,
    phase: "countdown",
    left: COUNTDOWN_TICKS,
    puck: { x: W / 2, y: H * 0.7, vx: 0, vy: 0 },
    player: { ...PLAYER_HOME, vx: 0, vy: 0 },
    ai: { ...AI_HOME, vx: 0, vy: 0 },
    score: { player: 0, ai: 0 },
    serveTo: "player",
    lastScorer: null,
    rng: seed >>> 0,
    mem: { tx: AI_HOME.x, ty: AI_HOME.y, wait: 0, aim: null },
    stall: 0,
    inHalf: 0,
    outcome: null
  };
  servePuck(s, "player");
  return s;
}
function moveMallet(m, tx, ty, speed, top) {
  const lo = top ? MALLET_R : MID + MALLET_R;
  const hi = top ? MID - MALLET_R : H - MALLET_R;
  tx = clamp(tx, MALLET_R, W - MALLET_R);
  ty = clamp(ty, lo, hi);
  const dx = tx - m.x;
  const dy = ty - m.y;
  const d = Math.sqrt(dx * dx + dy * dy);
  const step2 = speed * DT;
  let nx = tx;
  let ny = ty;
  if (d > step2) {
    nx = m.x + dx / d * step2;
    ny = m.y + dy / d * step2;
  }
  m.vx = (nx - m.x) / DT;
  m.vy = (ny - m.y) / DT;
  m.x = nx;
  m.y = ny;
}
function capSpeed(p) {
  const v2 = p.vx * p.vx + p.vy * p.vy;
  if (v2 > PUCK_MAX * PUCK_MAX) {
    const k = PUCK_MAX / Math.sqrt(v2);
    p.vx *= k;
    p.vy *= k;
  }
}
function hitMallet(p, m, by, events) {
  const dx = p.x - m.x;
  const dy = p.y - m.y;
  const reach = PUCK_R + MALLET_R;
  const d2 = dx * dx + dy * dy;
  if (d2 >= reach * reach) return false;
  const d = Math.sqrt(d2);
  const nx = d > 1e-9 ? dx / d : 0;
  const ny = d > 1e-9 ? dy / d : by === "player" ? -1 : 1;
  p.x = m.x + nx * reach;
  p.y = m.y + ny * reach;
  const rel = (p.vx - m.vx) * nx + (p.vy - m.vy) * ny;
  if (rel < 0) {
    p.vx -= (1 + MALLET_E) * rel * nx;
    p.vy -= (1 + MALLET_E) * rel * ny;
    capSpeed(p);
    events.push({ type: "hit", by, power: Math.min(1, -rel / 2200) });
  }
  return true;
}
function hitPost(p, px, py) {
  const dx = p.x - px;
  const dy = p.y - py;
  const d2 = dx * dx + dy * dy;
  if (d2 >= PUCK_R * PUCK_R || d2 < 1e-9) return 0;
  const d = Math.sqrt(d2);
  const nx = dx / d;
  const ny = dy / d;
  p.x = px + nx * PUCK_R;
  p.y = py + ny * PUCK_R;
  const rel = p.vx * nx + p.vy * ny;
  if (rel < 0) {
    p.vx -= (1 + WALL_E) * rel * nx;
    p.vy -= (1 + WALL_E) * rel * ny;
    return -rel;
  }
  return 0;
}
function walls(p) {
  let impact = 0;
  if (p.x < PUCK_R) {
    p.x = PUCK_R;
    if (p.vx < 0) {
      impact = Math.max(impact, -p.vx);
      p.vx = -p.vx * WALL_E;
    }
  } else if (p.x > W - PUCK_R) {
    p.x = W - PUCK_R;
    if (p.vx > 0) {
      impact = Math.max(impact, p.vx);
      p.vx = -p.vx * WALL_E;
    }
  }
  const inMouth = p.x > GOAL_X0 && p.x < GOAL_X1;
  if (inMouth) {
    if (p.y < 0) return { impact, goal: "player" };
    if (p.y > H) return { impact, goal: "ai" };
    impact = Math.max(impact, hitPost(p, GOAL_X0, 0), hitPost(p, GOAL_X1, 0), hitPost(p, GOAL_X0, H), hitPost(p, GOAL_X1, H));
  } else {
    if (p.y < PUCK_R) {
      p.y = PUCK_R;
      if (p.vy < 0) {
        impact = Math.max(impact, -p.vy);
        p.vy = -p.vy * WALL_E;
      }
    } else if (p.y > H - PUCK_R) {
      p.y = H - PUCK_R;
      if (p.vy > 0) {
        impact = Math.max(impact, p.vy);
        p.vy = -p.vy * WALL_E;
      }
    }
  }
  return { impact, goal: null };
}
function scoreGoal(s, scorer, events) {
  s.score = { ...s.score, [scorer]: s.score[scorer] + 1 };
  s.lastScorer = scorer;
  s.serveTo = scorer === "player" ? "ai" : "player";
  s.phase = "goal";
  s.left = GOAL_TICKS;
  s.puck = { x: s.puck.x, y: scorer === "player" ? -PUCK_R * 2 : H + PUCK_R * 2, vx: 0, vy: 0 };
  events.push({ type: "goal", scorer });
}
function finish(s, events) {
  const { player, ai } = s.score;
  s.outcome = player > ai ? "won" : player < ai ? "lost" : "draw";
  s.phase = "over";
  s.left = 0;
  events.push({ type: "over", outcome: s.outcome });
}
function step(s, input, events = []) {
  if (s.phase === "over") return s;
  s.tick++;
  const target = clampInput(input.x, input.y);
  const r = createRng(s.rng);
  s.mem = aiThink(s, r);
  s.rng = r.state();
  const aiSpeed = AI_LEVELS[s.level].speed;
  const live = s.phase === "play";
  for (let k = 0; k < SUB; k++) {
    moveMallet(s.player, target.x, target.y, PLAYER_SPEED, false);
    moveMallet(s.ai, s.mem.tx, s.mem.ty, aiSpeed, true);
    if (!live) {
      s.player.vx = s.player.vy = s.ai.vx = s.ai.vy = 0;
      continue;
    }
    const p = s.puck;
    p.x += p.vx * DT;
    p.y += p.vy * DT;
    p.vx *= FRICTION;
    p.vy *= FRICTION;
    const hitP = hitMallet(p, s.player, "player", events);
    const hitA = hitMallet(p, s.ai, "ai", events);
    if (hitP || hitA) s.stall = 0;
    const w = walls(p);
    if (w.goal) {
      scoreGoal(s, w.goal, events);
      break;
    }
    if (hitMallet(p, s.player, "player", events) || hitMallet(p, s.ai, "ai", events)) walls(p);
    if (w.impact > 120) events.push({ type: "wall", power: Math.min(1, w.impact / 2200) });
  }
  if (s.phase === "play") {
    const p = s.puck;
    const slow = p.vx * p.vx + p.vy * p.vy < 45 * 45;
    s.stall = slow ? s.stall + 1 : 0;
    if (p.y > MID) s.inHalf = s.inHalf > 0 ? s.inHalf + 1 : 1;
    else s.inHalf = s.inHalf < 0 ? s.inHalf - 1 : -1;
    if (s.stall > STALL_TICKS) {
      p.vx = (W / 2 - p.x) * 0.9;
      p.vy = p.y > MID ? -420 : 420;
      s.stall = 0;
    } else if (Math.abs(s.inHalf) > HALF_TICKS) {
      s.phase = "serve";
      s.left = SERVE_TICKS;
      servePuck(s, s.inHalf > 0 ? "ai" : "player");
    }
  } else if (s.phase === "countdown") {
    if (s.left % TICK_HZ === 0 && s.left > 0) events.push({ type: "count", n: s.left / TICK_HZ });
    if (--s.left <= 0) {
      s.phase = "play";
      events.push({ type: "go" });
    }
  } else if (s.phase === "goal") {
    if (--s.left <= 0) {
      if (s.score.player >= WIN_SCORE || s.score.ai >= WIN_SCORE) finish(s, events);
      else {
        s.phase = "serve";
        s.left = SERVE_TICKS;
        servePuck(s, s.serveTo);
      }
    }
  } else if (s.phase === "serve") {
    if (--s.left <= 0) s.phase = "play";
  }
  if (s.outcome === null && s.tick >= MAX_TICKS) finish(s, events);
  return s;
}

// src/games/airhockey/replay.ts
var PREFIX = "a1:";
var MAX_LOG_CHARS = 2e5;
var unzig = (n) => n >>> 1 ^ -(n & 1);
function decodeLog(log, maxTicks = MAX_TICKS) {
  if (typeof log !== "string" || !log.startsWith(PREFIX) || log.length > MAX_LOG_CHARS) return null;
  let bin;
  try {
    bin = atob(log.slice(PREFIX.length));
  } catch {
    return null;
  }
  let at = 0;
  const read = () => {
    let v = 0;
    let shift = 0;
    for (; ; ) {
      if (at >= bin.length || shift > 28) return null;
      const b = bin.charCodeAt(at++);
      v |= (b & 127) << shift;
      if (b < 128) return v >>> 0;
      shift += 7;
    }
  };
  const x0 = read();
  const y0 = read();
  if (x0 === null || y0 === null) return null;
  const out = [{ x: x0, y: y0 }];
  let x = x0;
  let y = y0;
  while (at < bin.length) {
    const a = read();
    const b = read();
    const r = read();
    if (a === null || b === null || r === null) return null;
    const dx = unzig(a);
    const dy = unzig(b);
    if (out.length + r + 1 > maxTicks) return null;
    for (let k = 0; k <= r; k++) {
      x += dx;
      y += dy;
      if (x < 0 || y < 0 || x > 5e3 || y > 5e3) return null;
      out.push({ x, y });
    }
  }
  return out;
}
function replayMatch(seed, level, log) {
  const inputs = decodeLog(log);
  if (!inputs) return null;
  const s = createMatch(seed, level);
  for (let i = 0; i < inputs.length; i++) {
    if (s.phase === "over") return null;
    step(s, inputs[i]);
  }
  return s.phase === "over" ? { state: s, ticks: inputs.length } : null;
}

// src/casino/server/handler.ts
var CasinoStoreError = class extends Error {
  constructor(code) {
    super(code);
    this.code = code;
  }
};
var STATUS = {
  unauthorized: 401,
  account_required: 403,
  insufficient_funds: 402,
  invalid_bet: 400,
  conflict: 409,
  rate_limited: 429,
  bad_request: 400,
  game_disabled: 423,
  server: 500
};
var fail = (code) => ({ status: STATUS[code], body: { code } });
var ok = (body) => ({ status: 200, body });
var MAX_STAKE = 1e5;
var MAX_ROULETTE_BETS = 60;
var BET_TYPES = ["straight", "red", "black", "even", "odd", "low", "high", "dozen", "column"];
function parseBets(x) {
  if (!Array.isArray(x) || x.length === 0 || x.length > MAX_ROULETTE_BETS) return null;
  const out = [];
  let total = 0;
  for (const raw of x) {
    if (!raw || typeof raw !== "object") return null;
    const b = raw;
    const type = b.type;
    if (!BET_TYPES.includes(type)) return null;
    if (typeof b.amount !== "number" || !Number.isInteger(b.amount) || b.amount < 1) return null;
    let value;
    if (type === "straight") {
      if (typeof b.value !== "number" || !Number.isInteger(b.value) || b.value < 0 || b.value > 36) return null;
      value = b.value;
    } else if (type === "dozen" || type === "column") {
      if (typeof b.value !== "number" || !Number.isInteger(b.value) || b.value < 1 || b.value > 3) return null;
      value = b.value;
    } else if (b.value !== void 0) return null;
    total += b.amount;
    out.push(value === void 0 ? { type, amount: b.amount } : { type, value, amount: b.amount });
  }
  return total <= MAX_STAKE ? out : null;
}
var stakeOf = (bets) => bets.reduce((s, b) => s + b.amount, 0);
function bjView(row, balance) {
  const s = row.state;
  const hidden = s.phase === "PLAYER";
  return {
    requestId: row.requestId,
    phase: s.phase,
    hands: s.hands,
    active: s.active,
    dealer: s.dealer.map((c, i) => hidden && i === 1 ? null : c),
    results: s.results,
    stake: row.stake,
    balance
  };
}
var premiumReceipt = (b) => ({
  requestId: b.requestId,
  machine: b.detail.machine,
  bet: b.stake,
  draws: b.detail.draws,
  payout: b.payout,
  balance: b.balance,
  at: b.at
});
async function handleCasinoRequest(req, deps) {
  if (!req.user) return fail("unauthorized");
  const user = req.user;
  if (deps.allow && !deps.allow(user.id)) return fail("rate_limited");
  const rng = deps.rng ?? cryptoRng;
  const seed = deps.seed ?? secureSeed;
  const store2 = deps.store;
  try {
    if (req.method === "GET") {
      if (!user.registered) return fail("account_required");
      const url = new URL(req.url);
      if (url.searchParams.has("balance")) return ok({ balance: (await store2.account(user.id)).balance });
      const requestId2 = url.searchParams.get("requestId");
      if (!isRequestId(requestId2)) return fail("invalid_bet");
      const found = await store2.find(user.id, requestId2.toLowerCase());
      return found && found.game === "premium" ? ok(premiumReceipt(found)) : { status: 404, body: { found: false } };
    }
    if (req.method !== "POST") return fail("bad_request");
    const b = req.body && typeof req.body === "object" ? req.body : {};
    if (b.op === void 0) {
      if (!user.registered) return fail("account_required");
      const { requestId: requestId2, machine, bet } = b;
      if (!isRequestId(requestId2) || !isMachineId(machine) || !isValidBetFor(MACHINES[machine], bet)) return fail("invalid_bet");
      const id = requestId2.toLowerCase();
      const existing = await store2.find(user.id, id);
      if (existing) return existing.game === "premium" && existing.detail.machine === machine && existing.stake === bet ? ok(premiumReceipt(existing)) : fail("conflict");
      if (deps.gameEnabled && !await deps.gameEnabled("slots")) return fail("game_disabled");
      const round = playRound(MACHINES[machine], bet, deps.random ?? cryptoUint32);
      const booked = await store2.play({ userId: user.id, requestId: id, game: "premium", stake: bet, payout: round.payout, detail: { machine, draws: round.draws } });
      if (booked.detail.machine !== machine) return fail("conflict");
      return ok(premiumReceipt(booked));
    }
    if (b.op === "account") return ok(await store2.account(user.id));
    if (!user.registered) return fail("account_required");
    const requestId = typeof b.requestId === "string" && isRequestId(b.requestId) ? b.requestId.toLowerCase() : null;
    switch (b.op) {
      case "claim": {
        if (!requestId) return fail("bad_request");
        return ok(await store2.claimBonus(user.id, requestId));
      }
      case "roulette": {
        const bets = parseBets(b.bets);
        if (!requestId || !bets) return fail("invalid_bet");
        const stake = stakeOf(bets);
        const existing = await store2.find(user.id, requestId);
        if (existing) {
          if (existing.game !== "roulette" || existing.stake !== stake) return fail("conflict");
          return ok({ requestId, pocket: existing.detail.pocket, stake, payout: existing.payout, balance: existing.balance });
        }
        if (deps.gameEnabled && !await deps.gameEnabled("roulette")) return fail("game_disabled");
        const pocket = spin(rng());
        const booked = await store2.play({ userId: user.id, requestId, game: "roulette", stake, payout: totalPayout(bets, pocket), detail: { pocket, bets } });
        return ok({ requestId, pocket: booked.detail.pocket, stake, payout: booked.payout, balance: booked.balance });
      }
      case "slots": {
        const { lines: lines2, betPerLine } = b;
        if (!requestId || !LINE_OPTIONS.includes(lines2) || !BET_PER_LINE.includes(betPerLine)) return fail("invalid_bet");
        const l = lines2;
        const bpl = betPerLine;
        const stake = l * bpl;
        const existing = await store2.find(user.id, requestId);
        const answer = (bk) => ({ requestId, stops: bk.detail.stops, lines: l, betPerLine: bpl, payout: bk.payout, balance: bk.balance });
        if (existing) return existing.game === "slots" && existing.stake === stake && existing.detail.lines === l ? ok(answer(existing)) : fail("conflict");
        if (deps.gameEnabled && !await deps.gameEnabled("slots")) return fail("game_disabled");
        const stops = spinReels(rng());
        const outcome = evaluateSpin2(stops, l, bpl);
        return ok(answer(await store2.play({ userId: user.id, requestId, game: "slots", stake, payout: outcome.total, detail: { stops, lines: l, betPerLine: bpl } })));
      }
      case "bj": {
        const row = await store2.bjLoad(user.id);
        const { balance } = await store2.account(user.id);
        return ok({ table: row ? bjView(row, balance) : null, balance });
      }
      case "bj_deal": {
        const bet = b.bet;
        if (!requestId || typeof bet !== "number" || !Number.isInteger(bet) || bet < 1 || bet > MAX_STAKE) return fail("invalid_bet");
        const current = await store2.bjLoad(user.id);
        if (current) {
          if (current.requestId !== requestId) return fail("conflict");
          return ok(bjView(current, (await store2.account(user.id)).balance));
        }
        if (deps.gameEnabled && !await deps.gameEnabled("blackjack")) return fail("game_disabled");
        const state = deal(createBlackjack(seed()), bet);
        let balance = await store2.bjOpen(user.id, requestId, bet, state);
        if (state.phase === "SETTLED") {
          balance = await store2.bjStep(user.id, requestId, 1, 0, state, totalPayout2(state), finalDetail(state));
        }
        return ok(bjView({ requestId, stake: bet, state }, balance));
      }
      case "bj_act": {
        const action = b.action;
        if (!requestId || action !== "hit" && action !== "stand" && action !== "double" && action !== "split") return fail("bad_request");
        const row = await store2.bjLoad(user.id);
        if (!row || row.requestId !== requestId || row.state.phase !== "PLAYER") return fail("conflict");
        const s = row.state;
        if (action === "double" && !canDouble(s)) return fail("bad_request");
        if (action === "split" && !canSplit(s)) return fail("bad_request");
        const extra = action === "double" || action === "split" ? extraStake(s, action) : 0;
        const next = action === "hit" ? hit(s) : action === "stand" ? stand(s) : action === "double" ? double(s) : split(s);
        const settled = next.phase === "SETTLED";
        const balance = await store2.bjStep(user.id, requestId, row.version, extra, next, settled ? totalPayout2(next) : null, settled ? finalDetail(next) : null);
        return ok(bjView({ requestId, stake: row.stake + extra, state: next }, balance));
      }
      case "ah_start": {
        const { stake, level } = b;
        if (!requestId || !AH_STAKES.includes(stake) || !isAiLevel(level)) return fail("invalid_bet");
        const found = await store2.ahGet(user.id, requestId);
        if (!found && deps.gameEnabled && !await deps.gameEnabled("airhockey")) return fail("game_disabled");
        const opened = await store2.ahOpen(user.id, requestId, stake, level, seed() >>> 0);
        return ok({ requestId, seed: opened.seed, level: opened.level, stake, balance: opened.balance });
      }
      case "ah_finish": {
        if (!requestId || typeof b.log !== "string" || b.log.length > MAX_LOG_CHARS) return fail("bad_request");
        const match = await store2.ahGet(user.id, requestId);
        if (!match) return fail("conflict");
        const answer = (m, balance) => ({
          requestId,
          outcome: m.status === "open" ? "lost" : m.status,
          score: m.scorePlayer === null || m.scoreAi === null ? null : { player: m.scorePlayer, ai: m.scoreAi },
          stake: match.stake,
          payout: m.payout,
          balance
        });
        if (match.status !== "open") return ok(answer(match, (await store2.account(user.id)).balance));
        const replay = replayMatch(match.seed, match.level, b.log);
        if (!replay || !replay.state.outcome) return fail("bad_request");
        const { score, outcome } = replay.state;
        const closed = await store2.ahClose(user.id, requestId, outcome, score.player, score.ai, replay.ticks);
        return ok(answer(closed, closed.balance));
      }
      default:
        return fail("bad_request");
    }
  } catch (e) {
    if (e instanceof CasinoStoreError) return fail(e.code === "not_registered" ? "account_required" : e.code);
    throw e;
  }
}
function finalDetail(s) {
  return { hands: s.hands, dealer: s.dealer, results: s.results };
}

// supabase/functions/_shared/casinoStore.ts
var toBooking = (r) => ({
  requestId: r.request_id,
  game: r.game,
  stake: Number(r.stake),
  payout: Number(r.payout),
  balance: Number(r.balance),
  detail: r.detail ?? {},
  at: Date.parse(r.created_at)
});
function postgrestCasinoStore(supabaseUrl, serviceKey, fetchImpl = fetch) {
  async function rpc(fn, args) {
    const res = await fetchImpl(`${supabaseUrl}/rest/v1/rpc/${fn}`, {
      method: "POST",
      headers: { "content-type": "application/json", apikey: serviceKey, authorization: `Bearer ${serviceKey}` },
      body: JSON.stringify(args)
    });
    const body = await res.json().catch(() => null);
    if (!res.ok) {
      const code = body?.code;
      if (code === "P0402") throw new CasinoStoreError("insufficient_funds");
      if (code === "P0409") throw new CasinoStoreError("conflict");
      if (code === "P0400") throw new CasinoStoreError("invalid_bet");
      if (code === "P0403") throw new CasinoStoreError("not_registered");
      if (code === "P0423") throw new CasinoStoreError("game_disabled");
      throw new Error(`rpc ${fn} failed: ${res.status}`);
    }
    return body;
  }
  return {
    async account(userId) {
      const rows = await rpc("account_wallet", { p_user: userId });
      const r = rows[0];
      return { balance: Number(r?.balance ?? 0), bonusClaimed: !!r?.bonus_claimed, registered: !!r?.registered };
    },
    async claimBonus(userId, requestId) {
      const rows = await rpc("account_claim_bonus", { p_user: userId, p_request: requestId });
      return { balance: Number(rows[0].balance), granted: rows[0].granted };
    },
    async play(c) {
      const rows = await rpc("account_play", { p_user: c.userId, p_request: c.requestId, p_game: c.game, p_stake: c.stake, p_payout: c.payout, p_detail: c.detail });
      if (!rows?.length) throw new Error("empty booking");
      return { ...toBooking(rows[0]), replayed: !!rows[0].replayed };
    },
    async find(userId, requestId) {
      const rows = await rpc("account_find", { p_user: userId, p_request: requestId });
      return rows?.length ? toBooking(rows[0]) : null;
    },
    async bjLoad(userId) {
      const row = await rpc("bj_load", { p_user: userId });
      return row ? { requestId: row.request_id, stake: Number(row.stake), state: row.state, version: row.version } : null;
    },
    async bjOpen(userId, requestId, stake, state) {
      return Number(await rpc("bj_open", { p_user: userId, p_request: requestId, p_stake: stake, p_state: state }));
    },
    async bjStep(userId, requestId, version, extra, state, payout, detail) {
      return Number(
        await rpc("bj_step", { p_user: userId, p_request: requestId, p_version: version, p_extra: extra, p_state: state, p_payout: payout, p_detail: detail })
      );
    },
    async ahOpen(userId, requestId, stake, level, seed) {
      const rows = await rpc("ah_open", { p_user: userId, p_request: requestId, p_stake: stake, p_level: level, p_seed: seed });
      const r = rows[0];
      return { balance: Number(r.balance), seed: Number(r.seed), level: r.level, replayed: false };
    },
    async ahGet(userId, requestId) {
      const m = await rpc("ah_get", {
        p_user: userId,
        p_request: requestId
      });
      return m ? { stake: Number(m.stake), level: m.level, seed: Number(m.seed), status: m.status, scorePlayer: m.score_player, scoreAi: m.score_ai, payout: Number(m.payout) } : null;
    },
    async ahClose(userId, requestId, outcome, player, ai, ticks) {
      const rows = await rpc("ah_close", {
        p_user: userId,
        p_request: requestId,
        p_outcome: outcome,
        p_player: player,
        p_ai: ai,
        p_ticks: ticks
      });
      const r = rows[0];
      return { balance: Number(r.balance), status: r.status, payout: Number(r.payout), scorePlayer: r.score_player, scoreAi: r.score_ai };
    }
  };
}

// supabase/functions/casino/source.ts
var SUPABASE_URL = Deno.env.get("SUPABASE_URL");
var ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY");
var SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
var ALLOWED = /* @__PURE__ */ new Set(["https://siiknotic.github.io", "http://localhost:5173", "http://127.0.0.1:5173", "http://localhost:4173"]);
var store = postgrestCasinoStore(SUPABASE_URL, SERVICE_KEY);
async function gameEnabled(game) {
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/game_enabled`, {
      method: "POST",
      headers: { "content-type": "application/json", apikey: SERVICE_KEY, authorization: `Bearer ${SERVICE_KEY}` },
      body: JSON.stringify({ p_game: game })
    });
    return res.ok && await res.json() === true;
  } catch {
    return false;
  }
}
var hits = /* @__PURE__ */ new Map();
function allow(userId) {
  const now = Date.now();
  const recent = (hits.get(userId) ?? []).filter((t) => now - t < 1e3);
  recent.push(now);
  hits.set(userId, recent);
  if (hits.size > 1e4) hits.clear();
  return recent.length <= 8;
}
async function verifiedUser(req) {
  const auth = req.headers.get("authorization") ?? "";
  if (!auth.startsWith("Bearer ")) return null;
  const res = await fetch(`${SUPABASE_URL}/auth/v1/user`, { headers: { apikey: ANON_KEY, authorization: auth } });
  if (!res.ok) return null;
  const u = await res.json().catch(() => null);
  if (typeof u?.id !== "string") return null;
  return { id: u.id, registered: u.is_anonymous !== true && typeof u.email_confirmed_at === "string" };
}
Deno.serve(async (req) => {
  const origin = req.headers.get("origin") ?? "";
  const cors = {
    "access-control-allow-origin": ALLOWED.has(origin) ? origin : "https://siiknotic.github.io",
    "access-control-allow-headers": "authorization, apikey, content-type, x-client-info",
    "access-control-allow-methods": "GET, POST, OPTIONS",
    vary: "origin"
  };
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
  let body = null;
  if (req.method === "POST") {
    const text = await req.text();
    const limit = text.startsWith('{"op":"ah_finish"') ? 204800 : 4096;
    if (text.length > limit) return Response.json({ code: "bad_request" }, { status: 413, headers: cors });
    try {
      body = JSON.parse(text);
    } catch {
      return Response.json({ code: "bad_request" }, { status: 400, headers: cors });
    }
  }
  try {
    const out = await handleCasinoRequest({ method: req.method, url: req.url, user: await verifiedUser(req), body }, { store, allow, gameEnabled });
    return Response.json(out.body, { status: out.status, headers: { ...cors, "cache-control": "no-store" } });
  } catch (e) {
    console.error("casino", e instanceof Error ? e.message : e);
    return Response.json({ code: "server" }, { status: 500, headers: cors });
  }
});
